# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import assistant_pb2 as assistant__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StrategyAssistantStub:
    """============================================================================
    The LLM-backed strategy assistant, over gRPC.

    This contract is deliberately SEPARATE from calculator.proto and
    finance.proto. Those speak in strategies, legs, payoff curves and closed-
    form financial functions -- deterministic, auditable arithmetic. This one
    wraps a fine-tuned language model that turns a trader's free-text utterance
    ("bullish on NVDA into earnings, thirty days out") into the structured
    parameters CalculateStrategy actually needs. The two must not be conflated:
    nothing in this file computes a price, a Greek or a payoff, and nothing in
    calculator.proto or finance.proto ever guesses at what a human meant.

    ---------------------------------------------------------------------------
    ON THE oneof IN ParseResponse -- read this before adding a branch.

    A single ParseRequest can end in exactly three ways, and they are not
    gradations of the same outcome:

    1. The model understood the trade well enough to emit parameters.
    2. The model understood there IS a trade in there somewhere, but is
    missing one fact it cannot honestly default (which expiration? how
    many contracts?), so it asks a single clarifying question instead of
    guessing.
    3. The utterance cannot be turned into a trade at all -- an unsupported
    strategy, a symbol that resolves to nothing real, or a request that
    was never about a strategy in the first place -- and the honest
    response is a refusal, not a fabricated guess.

    Both (2) and (3) return gRPC status OK. This is deliberate, not an
    oversight: a clarifying question is the model doing its job correctly, and
    so is a refusal when the alternative would be inventing a symbol, a
    strategy or an expiration that was never actually stated. Real-data-only is
    binding project policy everywhere else in this codebase -- market quotes
    are never fabricated -- and this contract extends the same discipline to
    intent: a guess dressed up as a parse is exactly as dishonest as a
    fabricated quote. If either branch were instead encoded as a gRPC error,
    every well-behaved back-and-forth with a trader would register as a
    failure in gRPC metrics, in Envoy's access logs and in the browser client's
    error handling -- indistinguishable from the model actually being down.
    The oneof keeps "succeeded, asked a question" and "succeeded, declined"
    distinguishable from each other and from "the RPC itself failed", which is
    the only case that should still surface as a gRPC error (an unreachable
    inference backend, a malformed request, and so on).
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseStrategy = channel.unary_unary(
                '/calculator.assistant.StrategyAssistant/ParseStrategy',
                request_serializer=assistant__pb2.ParseRequest.SerializeToString,
                response_deserializer=assistant__pb2.ParseResponse.FromString,
                _registered_method=True)


class StrategyAssistantServicer:
    """============================================================================
    The LLM-backed strategy assistant, over gRPC.

    This contract is deliberately SEPARATE from calculator.proto and
    finance.proto. Those speak in strategies, legs, payoff curves and closed-
    form financial functions -- deterministic, auditable arithmetic. This one
    wraps a fine-tuned language model that turns a trader's free-text utterance
    ("bullish on NVDA into earnings, thirty days out") into the structured
    parameters CalculateStrategy actually needs. The two must not be conflated:
    nothing in this file computes a price, a Greek or a payoff, and nothing in
    calculator.proto or finance.proto ever guesses at what a human meant.

    ---------------------------------------------------------------------------
    ON THE oneof IN ParseResponse -- read this before adding a branch.

    A single ParseRequest can end in exactly three ways, and they are not
    gradations of the same outcome:

    1. The model understood the trade well enough to emit parameters.
    2. The model understood there IS a trade in there somewhere, but is
    missing one fact it cannot honestly default (which expiration? how
    many contracts?), so it asks a single clarifying question instead of
    guessing.
    3. The utterance cannot be turned into a trade at all -- an unsupported
    strategy, a symbol that resolves to nothing real, or a request that
    was never about a strategy in the first place -- and the honest
    response is a refusal, not a fabricated guess.

    Both (2) and (3) return gRPC status OK. This is deliberate, not an
    oversight: a clarifying question is the model doing its job correctly, and
    so is a refusal when the alternative would be inventing a symbol, a
    strategy or an expiration that was never actually stated. Real-data-only is
    binding project policy everywhere else in this codebase -- market quotes
    are never fabricated -- and this contract extends the same discipline to
    intent: a guess dressed up as a parse is exactly as dishonest as a
    fabricated quote. If either branch were instead encoded as a gRPC error,
    every well-behaved back-and-forth with a trader would register as a
    failure in gRPC metrics, in Envoy's access logs and in the browser client's
    error handling -- indistinguishable from the model actually being down.
    The oneof keeps "succeeded, asked a question" and "succeeded, declined"
    distinguishable from each other and from "the RPC itself failed", which is
    the only case that should still surface as a gRPC error (an unreachable
    inference backend, a malformed request, and so on).
    ============================================================================

    """

    def ParseStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StrategyAssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseStrategy,
                    request_deserializer=assistant__pb2.ParseRequest.FromString,
                    response_serializer=assistant__pb2.ParseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.assistant.StrategyAssistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('calculator.assistant.StrategyAssistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StrategyAssistant:
    """============================================================================
    The LLM-backed strategy assistant, over gRPC.

    This contract is deliberately SEPARATE from calculator.proto and
    finance.proto. Those speak in strategies, legs, payoff curves and closed-
    form financial functions -- deterministic, auditable arithmetic. This one
    wraps a fine-tuned language model that turns a trader's free-text utterance
    ("bullish on NVDA into earnings, thirty days out") into the structured
    parameters CalculateStrategy actually needs. The two must not be conflated:
    nothing in this file computes a price, a Greek or a payoff, and nothing in
    calculator.proto or finance.proto ever guesses at what a human meant.

    ---------------------------------------------------------------------------
    ON THE oneof IN ParseResponse -- read this before adding a branch.

    A single ParseRequest can end in exactly three ways, and they are not
    gradations of the same outcome:

    1. The model understood the trade well enough to emit parameters.
    2. The model understood there IS a trade in there somewhere, but is
    missing one fact it cannot honestly default (which expiration? how
    many contracts?), so it asks a single clarifying question instead of
    guessing.
    3. The utterance cannot be turned into a trade at all -- an unsupported
    strategy, a symbol that resolves to nothing real, or a request that
    was never about a strategy in the first place -- and the honest
    response is a refusal, not a fabricated guess.

    Both (2) and (3) return gRPC status OK. This is deliberate, not an
    oversight: a clarifying question is the model doing its job correctly, and
    so is a refusal when the alternative would be inventing a symbol, a
    strategy or an expiration that was never actually stated. Real-data-only is
    binding project policy everywhere else in this codebase -- market quotes
    are never fabricated -- and this contract extends the same discipline to
    intent: a guess dressed up as a parse is exactly as dishonest as a
    fabricated quote. If either branch were instead encoded as a gRPC error,
    every well-behaved back-and-forth with a trader would register as a
    failure in gRPC metrics, in Envoy's access logs and in the browser client's
    error handling -- indistinguishable from the model actually being down.
    The oneof keeps "succeeded, asked a question" and "succeeded, declined"
    distinguishable from each other and from "the RPC itself failed", which is
    the only case that should still surface as a gRPC error (an unreachable
    inference backend, a malformed request, and so on).
    ============================================================================

    """

    @staticmethod
    def ParseStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/calculator.assistant.StrategyAssistant/ParseStrategy',
            assistant__pb2.ParseRequest.SerializeToString,
            assistant__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
