# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: assistant.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x61ssistant.proto\x12\x14\x63\x61lculator.assistant\">\n\x0cParseRequest\x12\x11\n\tutterance\x18\x01 \x01(\t\x12\x1b\n\x13prior_clarification\x18\x02 \x01(\t\"\xc2\x01\n\rParseResponse\x12\x36\n\x06params\x18\x01 \x01(\x0b\x32$.calculator.assistant.StrategyParamsH\x00\x12<\n\rclarification\x18\x02 \x01(\x0b\x32#.calculator.assistant.ClarificationH\x00\x12\x30\n\x07refusal\x18\x03 \x01(\x0b\x32\x1d.calculator.assistant.RefusalH\x00\x42\t\n\x07outcome\"\x8f\x01\n\x0eStrategyParams\x12\x0e\n\x06symbol\x18\x01 \x01(\t\x12\x13\n\x0b\x61sset_class\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\x12\x17\n\x0f\x65xpiration_days\x18\x04 \x01(\x05\x12\x10\n\x08quantity\x18\x05 \x01(\x05\x12\x1b\n\x13\x66\x61r_expiration_days\x18\x06 \x01(\x05\"!\n\rClarification\x12\x10\n\x08question\x18\x01 \x01(\t\"\xe0\x01\n\x07Refusal\x12\x34\n\x06reason\x18\x01 \x01(\x0e\x32$.calculator.assistant.Refusal.Reason\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x8d\x01\n\x06Reason\x12\x16\n\x12REASON_UNSPECIFIED\x10\x00\x12\x18\n\x14UNSUPPORTED_STRATEGY\x10\x01\x12\x12\n\x0eUNKNOWN_SYMBOL\x10\x02\x12\x10\n\x0cOUT_OF_SCOPE\x10\x03\x12\x15\n\x11MODEL_UNAVAILABLE\x10\x04\x12\x14\n\x10\x44\x41TA_UNAVAILABLE\x10\x05\x32m\n\x11StrategyAssistant\x12X\n\rParseStrategy\x12\".calculator.assistant.ParseRequest\x1a#.calculator.assistant.ParseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARSEREQUEST']._serialized_start=41
  _globals['_PARSEREQUEST']._serialized_end=103
  _globals['_PARSERESPONSE']._serialized_start=106
  _globals['_PARSERESPONSE']._serialized_end=300
  _globals['_STRATEGYPARAMS']._serialized_start=303
  _globals['_STRATEGYPARAMS']._serialized_end=446
  _globals['_CLARIFICATION']._serialized_start=448
  _globals['_CLARIFICATION']._serialized_end=481
  _globals['_REFUSAL']._serialized_start=484
  _globals['_REFUSAL']._serialized_end=708
  _globals['_REFUSAL_REASON']._serialized_start=567
  _globals['_REFUSAL_REASON']._serialized_end=708
  _globals['_STRATEGYASSISTANT']._serialized_start=710
  _globals['_STRATEGYASSISTANT']._serialized_end=819
# @@protoc_insertion_point(module_scope)
