# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import mortgage_assistant_pb2 as mortgage__assistant__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mortgage_assistant_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MortgageAssistantStub:
    """============================================================================
    The LLM-backed MORTGAGE / time-value-of-money assistant, over gRPC.

    @author Olumuyiwa Oluwasanmi

    This is the SECOND assistant contract in this binary and the fourth service
    on the port. It is the exact sibling of calculator.assistant.StrategyAssistant
    (proto/assistant.proto) -- same three-outcome shape, same reasoning about why
    two of those three outcomes are gRPC OK -- pointed at a different domain and
    backed by a DIFFERENT fine-tuned model.

    The two are deliberately separate contracts rather than one assistant with a
    mode flag. They emit different schemas from different training sets: the
    strategy model produces a symbol, an asset class and one of 48 catalogued
    option/futures strategies; this one produces the NAME OF A FINANCE RPC plus
    that RPC's own parameters. Folding them together would mean a `oneof` over
    two unrelated payloads guarded by a mode field nothing enforces, and a single
    misrouted request would be answered by a model that was never taught the
    question.

    WHAT THIS SERVICE IS FOR, precisely: turning "I have $172,300 saved and add
    $12,000 a year at 3.85%, over 37 years" into the arguments
    sensen.finance.Finance's ComputeFutureValueDetailed already accepts. It
    computes nothing. Every figure a caller ultimately shows a user comes from
    the Finance service actually running the operation this service named -- the
    same division of labour StrategyAssistant has with CalculateStrategy.

    It also gives no financial, tax or legal advice, and that is not a disclaimer
    bolted on here: it is in the model's own training system prompt, and the
    dataset that produced the model (agent/dataset/build_mortgage_dataset.py)
    teaches it to decline advice explicitly. A 0.6B model improvising an opinion
    on whether someone should refinance, on a page that computes real loan
    numbers, is the worst thing this could become.

    ---------------------------------------------------------------------------
    ON THE oneof IN ParseResponse -- read this before adding a branch.

    A single ParseRequest can end in exactly three ways, and they are not
    gradations of the same outcome:

    1. The model understood the request well enough to name an operation and
    fill in its parameters.
    2. The model understood there IS a calculation in there somewhere, but is
    missing one fact it cannot honestly default (over how many years? what
    rate?), so it asks a single clarifying question instead of guessing.
    3. The request cannot be turned into one of these operations at all -- an
    unsupported calculation, a request for advice, or something that was
    never about a loan or a cash flow in the first place -- and the honest
    response is a refusal, not a fabricated guess.

    Both (2) and (3) return gRPC status OK, for the reason assistant.proto's own
    banner gives and which applies here unchanged: a clarifying question is the
    model doing its job correctly, and so is a refusal when the alternative is
    inventing an interest rate, a term or a principal that was never stated. A
    fabricated PARAMETER is worse here than a fabricated symbol is there, because
    nothing downstream can catch it -- ComputeAmortization will happily amortize
    a principal the borrower never mentioned and return an exact, auditable,
    completely wrong schedule. Real-data-only policy is what forbids that, and
    this contract is where it is expressed.

    If either branch were instead encoded as a gRPC error, every well-behaved
    back-and-forth would register as a failure in gRPC metrics, in Envoy's access
    logs and in the browser client's error handling -- indistinguishable from the
    model being down. The oneof keeps "succeeded, asked a question" and
    "succeeded, declined" distinguishable from each other and from "the RPC
    itself failed", which is the only case that should still surface as a gRPC
    error (a full admission queue, a malformed request, and so on).
    ============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseOperation = channel.unary_unary(
                '/mortgage.assistant.MortgageAssistant/ParseOperation',
                request_serializer=mortgage__assistant__pb2.ParseRequest.SerializeToString,
                response_deserializer=mortgage__assistant__pb2.ParseResponse.FromString,
                _registered_method=True)


class MortgageAssistantServicer:
    """============================================================================
    The LLM-backed MORTGAGE / time-value-of-money assistant, over gRPC.

    @author Olumuyiwa Oluwasanmi

    This is the SECOND assistant contract in this binary and the fourth service
    on the port. It is the exact sibling of calculator.assistant.StrategyAssistant
    (proto/assistant.proto) -- same three-outcome shape, same reasoning about why
    two of those three outcomes are gRPC OK -- pointed at a different domain and
    backed by a DIFFERENT fine-tuned model.

    The two are deliberately separate contracts rather than one assistant with a
    mode flag. They emit different schemas from different training sets: the
    strategy model produces a symbol, an asset class and one of 48 catalogued
    option/futures strategies; this one produces the NAME OF A FINANCE RPC plus
    that RPC's own parameters. Folding them together would mean a `oneof` over
    two unrelated payloads guarded by a mode field nothing enforces, and a single
    misrouted request would be answered by a model that was never taught the
    question.

    WHAT THIS SERVICE IS FOR, precisely: turning "I have $172,300 saved and add
    $12,000 a year at 3.85%, over 37 years" into the arguments
    sensen.finance.Finance's ComputeFutureValueDetailed already accepts. It
    computes nothing. Every figure a caller ultimately shows a user comes from
    the Finance service actually running the operation this service named -- the
    same division of labour StrategyAssistant has with CalculateStrategy.

    It also gives no financial, tax or legal advice, and that is not a disclaimer
    bolted on here: it is in the model's own training system prompt, and the
    dataset that produced the model (agent/dataset/build_mortgage_dataset.py)
    teaches it to decline advice explicitly. A 0.6B model improvising an opinion
    on whether someone should refinance, on a page that computes real loan
    numbers, is the worst thing this could become.

    ---------------------------------------------------------------------------
    ON THE oneof IN ParseResponse -- read this before adding a branch.

    A single ParseRequest can end in exactly three ways, and they are not
    gradations of the same outcome:

    1. The model understood the request well enough to name an operation and
    fill in its parameters.
    2. The model understood there IS a calculation in there somewhere, but is
    missing one fact it cannot honestly default (over how many years? what
    rate?), so it asks a single clarifying question instead of guessing.
    3. The request cannot be turned into one of these operations at all -- an
    unsupported calculation, a request for advice, or something that was
    never about a loan or a cash flow in the first place -- and the honest
    response is a refusal, not a fabricated guess.

    Both (2) and (3) return gRPC status OK, for the reason assistant.proto's own
    banner gives and which applies here unchanged: a clarifying question is the
    model doing its job correctly, and so is a refusal when the alternative is
    inventing an interest rate, a term or a principal that was never stated. A
    fabricated PARAMETER is worse here than a fabricated symbol is there, because
    nothing downstream can catch it -- ComputeAmortization will happily amortize
    a principal the borrower never mentioned and return an exact, auditable,
    completely wrong schedule. Real-data-only policy is what forbids that, and
    this contract is where it is expressed.

    If either branch were instead encoded as a gRPC error, every well-behaved
    back-and-forth would register as a failure in gRPC metrics, in Envoy's access
    logs and in the browser client's error handling -- indistinguishable from the
    model being down. The oneof keeps "succeeded, asked a question" and
    "succeeded, declined" distinguishable from each other and from "the RPC
    itself failed", which is the only case that should still surface as a gRPC
    error (a full admission queue, a malformed request, and so on).
    ============================================================================

    """

    def ParseOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MortgageAssistantServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseOperation,
                    request_deserializer=mortgage__assistant__pb2.ParseRequest.FromString,
                    response_serializer=mortgage__assistant__pb2.ParseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mortgage.assistant.MortgageAssistant', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mortgage.assistant.MortgageAssistant', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MortgageAssistant:
    """============================================================================
    The LLM-backed MORTGAGE / time-value-of-money assistant, over gRPC.

    @author Olumuyiwa Oluwasanmi

    This is the SECOND assistant contract in this binary and the fourth service
    on the port. It is the exact sibling of calculator.assistant.StrategyAssistant
    (proto/assistant.proto) -- same three-outcome shape, same reasoning about why
    two of those three outcomes are gRPC OK -- pointed at a different domain and
    backed by a DIFFERENT fine-tuned model.

    The two are deliberately separate contracts rather than one assistant with a
    mode flag. They emit different schemas from different training sets: the
    strategy model produces a symbol, an asset class and one of 48 catalogued
    option/futures strategies; this one produces the NAME OF A FINANCE RPC plus
    that RPC's own parameters. Folding them together would mean a `oneof` over
    two unrelated payloads guarded by a mode field nothing enforces, and a single
    misrouted request would be answered by a model that was never taught the
    question.

    WHAT THIS SERVICE IS FOR, precisely: turning "I have $172,300 saved and add
    $12,000 a year at 3.85%, over 37 years" into the arguments
    sensen.finance.Finance's ComputeFutureValueDetailed already accepts. It
    computes nothing. Every figure a caller ultimately shows a user comes from
    the Finance service actually running the operation this service named -- the
    same division of labour StrategyAssistant has with CalculateStrategy.

    It also gives no financial, tax or legal advice, and that is not a disclaimer
    bolted on here: it is in the model's own training system prompt, and the
    dataset that produced the model (agent/dataset/build_mortgage_dataset.py)
    teaches it to decline advice explicitly. A 0.6B model improvising an opinion
    on whether someone should refinance, on a page that computes real loan
    numbers, is the worst thing this could become.

    ---------------------------------------------------------------------------
    ON THE oneof IN ParseResponse -- read this before adding a branch.

    A single ParseRequest can end in exactly three ways, and they are not
    gradations of the same outcome:

    1. The model understood the request well enough to name an operation and
    fill in its parameters.
    2. The model understood there IS a calculation in there somewhere, but is
    missing one fact it cannot honestly default (over how many years? what
    rate?), so it asks a single clarifying question instead of guessing.
    3. The request cannot be turned into one of these operations at all -- an
    unsupported calculation, a request for advice, or something that was
    never about a loan or a cash flow in the first place -- and the honest
    response is a refusal, not a fabricated guess.

    Both (2) and (3) return gRPC status OK, for the reason assistant.proto's own
    banner gives and which applies here unchanged: a clarifying question is the
    model doing its job correctly, and so is a refusal when the alternative is
    inventing an interest rate, a term or a principal that was never stated. A
    fabricated PARAMETER is worse here than a fabricated symbol is there, because
    nothing downstream can catch it -- ComputeAmortization will happily amortize
    a principal the borrower never mentioned and return an exact, auditable,
    completely wrong schedule. Real-data-only policy is what forbids that, and
    this contract is where it is expressed.

    If either branch were instead encoded as a gRPC error, every well-behaved
    back-and-forth would register as a failure in gRPC metrics, in Envoy's access
    logs and in the browser client's error handling -- indistinguishable from the
    model being down. The oneof keeps "succeeded, asked a question" and
    "succeeded, declined" distinguishable from each other and from "the RPC
    itself failed", which is the only case that should still surface as a gRPC
    error (a full admission queue, a malformed request, and so on).
    ============================================================================

    """

    @staticmethod
    def ParseOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mortgage.assistant.MortgageAssistant/ParseOperation',
            mortgage__assistant__pb2.ParseRequest.SerializeToString,
            mortgage__assistant__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
