// source: assistant.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var finance_pb = require('./finance_pb.js');
goog.object.extend(proto, finance_pb);
goog.exportSymbol('proto.calculator.assistant.Clarification', null, global);
goog.exportSymbol('proto.calculator.assistant.ParseRequest', null, global);
goog.exportSymbol('proto.calculator.assistant.ParseResponse', null, global);
goog.exportSymbol('proto.calculator.assistant.ParseResponse.OutcomeCase', null, global);
goog.exportSymbol('proto.calculator.assistant.Refusal', null, global);
goog.exportSymbol('proto.calculator.assistant.Refusal.Reason', null, global);
goog.exportSymbol('proto.calculator.assistant.StrategyParams', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.assistant.ParseRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.calculator.assistant.ParseRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.assistant.ParseRequest.displayName = 'proto.calculator.assistant.ParseRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.assistant.ParseResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.calculator.assistant.ParseResponse.oneofGroups_);
};
goog.inherits(proto.calculator.assistant.ParseResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.assistant.ParseResponse.displayName = 'proto.calculator.assistant.ParseResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.assistant.StrategyParams = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.calculator.assistant.StrategyParams, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.assistant.StrategyParams.displayName = 'proto.calculator.assistant.StrategyParams';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.assistant.Clarification = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.calculator.assistant.Clarification, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.assistant.Clarification.displayName = 'proto.calculator.assistant.Clarification';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.assistant.Refusal = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.calculator.assistant.Refusal, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.assistant.Refusal.displayName = 'proto.calculator.assistant.Refusal';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.assistant.ParseRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.assistant.ParseRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.assistant.ParseRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.ParseRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    utterance: jspb.Message.getFieldWithDefault(msg, 1, ""),
    priorClarification: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.assistant.ParseRequest}
 */
proto.calculator.assistant.ParseRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.assistant.ParseRequest;
  return proto.calculator.assistant.ParseRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.assistant.ParseRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.assistant.ParseRequest}
 */
proto.calculator.assistant.ParseRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUtterance(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPriorClarification(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.assistant.ParseRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.assistant.ParseRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.assistant.ParseRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.ParseRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUtterance();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPriorClarification();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string utterance = 1;
 * @return {string}
 */
proto.calculator.assistant.ParseRequest.prototype.getUtterance = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.calculator.assistant.ParseRequest} returns this
 */
proto.calculator.assistant.ParseRequest.prototype.setUtterance = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string prior_clarification = 2;
 * @return {string}
 */
proto.calculator.assistant.ParseRequest.prototype.getPriorClarification = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.calculator.assistant.ParseRequest} returns this
 */
proto.calculator.assistant.ParseRequest.prototype.setPriorClarification = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.calculator.assistant.ParseResponse.oneofGroups_ = [[1,2,3]];

/**
 * @enum {number}
 */
proto.calculator.assistant.ParseResponse.OutcomeCase = {
  OUTCOME_NOT_SET: 0,
  PARAMS: 1,
  CLARIFICATION: 2,
  REFUSAL: 3
};

/**
 * @return {proto.calculator.assistant.ParseResponse.OutcomeCase}
 */
proto.calculator.assistant.ParseResponse.prototype.getOutcomeCase = function() {
  return /** @type {proto.calculator.assistant.ParseResponse.OutcomeCase} */(jspb.Message.computeOneofCase(this, proto.calculator.assistant.ParseResponse.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.assistant.ParseResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.assistant.ParseResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.assistant.ParseResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.ParseResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    params: (f = msg.getParams()) && proto.calculator.assistant.StrategyParams.toObject(includeInstance, f),
    clarification: (f = msg.getClarification()) && proto.calculator.assistant.Clarification.toObject(includeInstance, f),
    refusal: (f = msg.getRefusal()) && proto.calculator.assistant.Refusal.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.assistant.ParseResponse}
 */
proto.calculator.assistant.ParseResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.assistant.ParseResponse;
  return proto.calculator.assistant.ParseResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.assistant.ParseResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.assistant.ParseResponse}
 */
proto.calculator.assistant.ParseResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.calculator.assistant.StrategyParams;
      reader.readMessage(value,proto.calculator.assistant.StrategyParams.deserializeBinaryFromReader);
      msg.setParams(value);
      break;
    case 2:
      var value = new proto.calculator.assistant.Clarification;
      reader.readMessage(value,proto.calculator.assistant.Clarification.deserializeBinaryFromReader);
      msg.setClarification(value);
      break;
    case 3:
      var value = new proto.calculator.assistant.Refusal;
      reader.readMessage(value,proto.calculator.assistant.Refusal.deserializeBinaryFromReader);
      msg.setRefusal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.assistant.ParseResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.assistant.ParseResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.assistant.ParseResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.ParseResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getParams();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.calculator.assistant.StrategyParams.serializeBinaryToWriter
    );
  }
  f = message.getClarification();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.calculator.assistant.Clarification.serializeBinaryToWriter
    );
  }
  f = message.getRefusal();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.calculator.assistant.Refusal.serializeBinaryToWriter
    );
  }
};


/**
 * optional StrategyParams params = 1;
 * @return {?proto.calculator.assistant.StrategyParams}
 */
proto.calculator.assistant.ParseResponse.prototype.getParams = function() {
  return /** @type{?proto.calculator.assistant.StrategyParams} */ (
    jspb.Message.getWrapperField(this, proto.calculator.assistant.StrategyParams, 1));
};


/**
 * @param {?proto.calculator.assistant.StrategyParams|undefined} value
 * @return {!proto.calculator.assistant.ParseResponse} returns this
*/
proto.calculator.assistant.ParseResponse.prototype.setParams = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.calculator.assistant.ParseResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.calculator.assistant.ParseResponse} returns this
 */
proto.calculator.assistant.ParseResponse.prototype.clearParams = function() {
  return this.setParams(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.calculator.assistant.ParseResponse.prototype.hasParams = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Clarification clarification = 2;
 * @return {?proto.calculator.assistant.Clarification}
 */
proto.calculator.assistant.ParseResponse.prototype.getClarification = function() {
  return /** @type{?proto.calculator.assistant.Clarification} */ (
    jspb.Message.getWrapperField(this, proto.calculator.assistant.Clarification, 2));
};


/**
 * @param {?proto.calculator.assistant.Clarification|undefined} value
 * @return {!proto.calculator.assistant.ParseResponse} returns this
*/
proto.calculator.assistant.ParseResponse.prototype.setClarification = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.calculator.assistant.ParseResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.calculator.assistant.ParseResponse} returns this
 */
proto.calculator.assistant.ParseResponse.prototype.clearClarification = function() {
  return this.setClarification(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.calculator.assistant.ParseResponse.prototype.hasClarification = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Refusal refusal = 3;
 * @return {?proto.calculator.assistant.Refusal}
 */
proto.calculator.assistant.ParseResponse.prototype.getRefusal = function() {
  return /** @type{?proto.calculator.assistant.Refusal} */ (
    jspb.Message.getWrapperField(this, proto.calculator.assistant.Refusal, 3));
};


/**
 * @param {?proto.calculator.assistant.Refusal|undefined} value
 * @return {!proto.calculator.assistant.ParseResponse} returns this
*/
proto.calculator.assistant.ParseResponse.prototype.setRefusal = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.calculator.assistant.ParseResponse.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.calculator.assistant.ParseResponse} returns this
 */
proto.calculator.assistant.ParseResponse.prototype.clearRefusal = function() {
  return this.setRefusal(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.calculator.assistant.ParseResponse.prototype.hasRefusal = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.assistant.StrategyParams.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.assistant.StrategyParams.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.assistant.StrategyParams} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.StrategyParams.toObject = function(includeInstance, msg) {
  var f, obj = {
    symbol: jspb.Message.getFieldWithDefault(msg, 1, ""),
    assetClass: jspb.Message.getFieldWithDefault(msg, 2, ""),
    strategy: jspb.Message.getFieldWithDefault(msg, 3, ""),
    expirationDays: jspb.Message.getFieldWithDefault(msg, 4, 0),
    quantity: jspb.Message.getFieldWithDefault(msg, 5, 0),
    farExpirationDays: jspb.Message.getFieldWithDefault(msg, 6, 0),
    exerciseType: jspb.Message.getFieldWithDefault(msg, 7, 0),
    asianType: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.assistant.StrategyParams}
 */
proto.calculator.assistant.StrategyParams.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.assistant.StrategyParams;
  return proto.calculator.assistant.StrategyParams.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.assistant.StrategyParams} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.assistant.StrategyParams}
 */
proto.calculator.assistant.StrategyParams.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSymbol(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAssetClass(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStrategy(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setExpirationDays(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFarExpirationDays(value);
      break;
    case 7:
      var value = /** @type {!proto.sensen.finance.ExerciseType} */ (reader.readEnum());
      msg.setExerciseType(value);
      break;
    case 8:
      var value = /** @type {!proto.sensen.finance.AsianType} */ (reader.readEnum());
      msg.setAsianType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.assistant.StrategyParams.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.assistant.StrategyParams.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.assistant.StrategyParams} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.StrategyParams.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSymbol();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAssetClass();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStrategy();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getExpirationDays();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getFarExpirationDays();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getExerciseType();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
  f = message.getAsianType();
  if (f !== 0.0) {
    writer.writeEnum(
      8,
      f
    );
  }
};


/**
 * optional string symbol = 1;
 * @return {string}
 */
proto.calculator.assistant.StrategyParams.prototype.getSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.calculator.assistant.StrategyParams} returns this
 */
proto.calculator.assistant.StrategyParams.prototype.setSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string asset_class = 2;
 * @return {string}
 */
proto.calculator.assistant.StrategyParams.prototype.getAssetClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.calculator.assistant.StrategyParams} returns this
 */
proto.calculator.assistant.StrategyParams.prototype.setAssetClass = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string strategy = 3;
 * @return {string}
 */
proto.calculator.assistant.StrategyParams.prototype.getStrategy = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.calculator.assistant.StrategyParams} returns this
 */
proto.calculator.assistant.StrategyParams.prototype.setStrategy = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 expiration_days = 4;
 * @return {number}
 */
proto.calculator.assistant.StrategyParams.prototype.getExpirationDays = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.assistant.StrategyParams} returns this
 */
proto.calculator.assistant.StrategyParams.prototype.setExpirationDays = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 quantity = 5;
 * @return {number}
 */
proto.calculator.assistant.StrategyParams.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.assistant.StrategyParams} returns this
 */
proto.calculator.assistant.StrategyParams.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 far_expiration_days = 6;
 * @return {number}
 */
proto.calculator.assistant.StrategyParams.prototype.getFarExpirationDays = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.assistant.StrategyParams} returns this
 */
proto.calculator.assistant.StrategyParams.prototype.setFarExpirationDays = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional sensen.finance.ExerciseType exercise_type = 7;
 * @return {!proto.sensen.finance.ExerciseType}
 */
proto.calculator.assistant.StrategyParams.prototype.getExerciseType = function() {
  return /** @type {!proto.sensen.finance.ExerciseType} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.sensen.finance.ExerciseType} value
 * @return {!proto.calculator.assistant.StrategyParams} returns this
 */
proto.calculator.assistant.StrategyParams.prototype.setExerciseType = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * optional sensen.finance.AsianType asian_type = 8;
 * @return {!proto.sensen.finance.AsianType}
 */
proto.calculator.assistant.StrategyParams.prototype.getAsianType = function() {
  return /** @type {!proto.sensen.finance.AsianType} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {!proto.sensen.finance.AsianType} value
 * @return {!proto.calculator.assistant.StrategyParams} returns this
 */
proto.calculator.assistant.StrategyParams.prototype.setAsianType = function(value) {
  return jspb.Message.setProto3EnumField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.assistant.Clarification.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.assistant.Clarification.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.assistant.Clarification} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.Clarification.toObject = function(includeInstance, msg) {
  var f, obj = {
    question: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.assistant.Clarification}
 */
proto.calculator.assistant.Clarification.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.assistant.Clarification;
  return proto.calculator.assistant.Clarification.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.assistant.Clarification} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.assistant.Clarification}
 */
proto.calculator.assistant.Clarification.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuestion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.assistant.Clarification.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.assistant.Clarification.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.assistant.Clarification} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.Clarification.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuestion();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string question = 1;
 * @return {string}
 */
proto.calculator.assistant.Clarification.prototype.getQuestion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.calculator.assistant.Clarification} returns this
 */
proto.calculator.assistant.Clarification.prototype.setQuestion = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.assistant.Refusal.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.assistant.Refusal.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.assistant.Refusal} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.Refusal.toObject = function(includeInstance, msg) {
  var f, obj = {
    reason: jspb.Message.getFieldWithDefault(msg, 1, 0),
    message: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.assistant.Refusal}
 */
proto.calculator.assistant.Refusal.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.assistant.Refusal;
  return proto.calculator.assistant.Refusal.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.assistant.Refusal} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.assistant.Refusal}
 */
proto.calculator.assistant.Refusal.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.calculator.assistant.Refusal.Reason} */ (reader.readEnum());
      msg.setReason(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.assistant.Refusal.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.assistant.Refusal.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.assistant.Refusal} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.assistant.Refusal.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getReason();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.calculator.assistant.Refusal.Reason = {
  REASON_UNSPECIFIED: 0,
  UNSUPPORTED_STRATEGY: 1,
  UNKNOWN_SYMBOL: 2,
  OUT_OF_SCOPE: 3,
  MODEL_UNAVAILABLE: 4,
  DATA_UNAVAILABLE: 5
};

/**
 * optional Reason reason = 1;
 * @return {!proto.calculator.assistant.Refusal.Reason}
 */
proto.calculator.assistant.Refusal.prototype.getReason = function() {
  return /** @type {!proto.calculator.assistant.Refusal.Reason} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.calculator.assistant.Refusal.Reason} value
 * @return {!proto.calculator.assistant.Refusal} returns this
 */
proto.calculator.assistant.Refusal.prototype.setReason = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.calculator.assistant.Refusal.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.calculator.assistant.Refusal} returns this
 */
proto.calculator.assistant.Refusal.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.calculator.assistant);
