/**
 * @fileoverview gRPC-Web generated client stub for calculator.assistant
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: assistant.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as assistant_pb from './assistant_pb'; // proto import: "assistant.proto"


export class StrategyAssistantClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorParseStrategy = new grpcWeb.MethodDescriptor(
    '/calculator.assistant.StrategyAssistant/ParseStrategy',
    grpcWeb.MethodType.UNARY,
    assistant_pb.ParseRequest,
    assistant_pb.ParseResponse,
    (request: assistant_pb.ParseRequest) => {
      return request.serializeBinary();
    },
    assistant_pb.ParseResponse.deserializeBinary
  );

  parseStrategy(
    request: assistant_pb.ParseRequest,
    metadata?: grpcWeb.Metadata | null): Promise<assistant_pb.ParseResponse>;

  parseStrategy(
    request: assistant_pb.ParseRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: assistant_pb.ParseResponse) => void): grpcWeb.ClientReadableStream<assistant_pb.ParseResponse>;

  parseStrategy(
    request: assistant_pb.ParseRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: assistant_pb.ParseResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/calculator.assistant.StrategyAssistant/ParseStrategy',
        request,
        metadata || {},
        this.methodDescriptorParseStrategy,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/calculator.assistant.StrategyAssistant/ParseStrategy',
    request,
    metadata || {},
    this.methodDescriptorParseStrategy);
  }

}

