/**
 * @fileoverview gRPC-Web generated client stub for calculator
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v4.25.1
// source: calculator.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as calculator_pb from './calculator_pb'; // proto import: "calculator.proto"


export class OptionsCalculatorClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCalculateStrategy = new grpcWeb.MethodDescriptor(
    '/calculator.OptionsCalculator/CalculateStrategy',
    grpcWeb.MethodType.UNARY,
    calculator_pb.StrategyRequest,
    calculator_pb.StrategyResponse,
    (request: calculator_pb.StrategyRequest) => {
      return request.serializeBinary();
    },
    calculator_pb.StrategyResponse.deserializeBinary
  );

  calculateStrategy(
    request: calculator_pb.StrategyRequest,
    metadata?: grpcWeb.Metadata | null): Promise<calculator_pb.StrategyResponse>;

  calculateStrategy(
    request: calculator_pb.StrategyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: calculator_pb.StrategyResponse) => void): grpcWeb.ClientReadableStream<calculator_pb.StrategyResponse>;

  calculateStrategy(
    request: calculator_pb.StrategyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: calculator_pb.StrategyResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/calculator.OptionsCalculator/CalculateStrategy',
        request,
        metadata || {},
        this.methodDescriptorCalculateStrategy,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/calculator.OptionsCalculator/CalculateStrategy',
    request,
    metadata || {},
    this.methodDescriptorCalculateStrategy);
  }

}

