// source: calculator.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.calculator.Greeks', null, global);
goog.exportSymbol('proto.calculator.Leg', null, global);
goog.exportSymbol('proto.calculator.Leg.Action', null, global);
goog.exportSymbol('proto.calculator.Leg.Type', null, global);
goog.exportSymbol('proto.calculator.PnLPoint', null, global);
goog.exportSymbol('proto.calculator.RiskMetrics', null, global);
goog.exportSymbol('proto.calculator.StrategyRequest', null, global);
goog.exportSymbol('proto.calculator.StrategyResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.Leg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.calculator.Leg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.Leg.displayName = 'proto.calculator.Leg';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.StrategyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.calculator.StrategyRequest.repeatedFields_, null);
};
goog.inherits(proto.calculator.StrategyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.StrategyRequest.displayName = 'proto.calculator.StrategyRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.Greeks = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.calculator.Greeks, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.Greeks.displayName = 'proto.calculator.Greeks';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.PnLPoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.calculator.PnLPoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.PnLPoint.displayName = 'proto.calculator.PnLPoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.RiskMetrics = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.calculator.RiskMetrics, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.RiskMetrics.displayName = 'proto.calculator.RiskMetrics';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.calculator.StrategyResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.calculator.StrategyResponse.repeatedFields_, null);
};
goog.inherits(proto.calculator.StrategyResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.calculator.StrategyResponse.displayName = 'proto.calculator.StrategyResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.Leg.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.Leg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.Leg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.Leg.toObject = function(includeInstance, msg) {
  var f, obj = {
action: jspb.Message.getFieldWithDefault(msg, 1, 0),
type: jspb.Message.getFieldWithDefault(msg, 2, 0),
strike: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
expirationDays: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
quantity: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.Leg}
 */
proto.calculator.Leg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.Leg;
  return proto.calculator.Leg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.Leg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.Leg}
 */
proto.calculator.Leg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.calculator.Leg.Action} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = /** @type {!proto.calculator.Leg.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setStrike(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setExpirationDays(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.Leg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.Leg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.Leg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.Leg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getStrike();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getExpirationDays();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.calculator.Leg.Action = {
  BUY: 0,
  SELL: 1
};

/**
 * @enum {number}
 */
proto.calculator.Leg.Type = {
  CALL: 0,
  PUT: 1,
  FUTURE: 2,
  STOCK: 3
};

/**
 * optional Action action = 1;
 * @return {!proto.calculator.Leg.Action}
 */
proto.calculator.Leg.prototype.getAction = function() {
  return /** @type {!proto.calculator.Leg.Action} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.calculator.Leg.Action} value
 * @return {!proto.calculator.Leg} returns this
 */
proto.calculator.Leg.prototype.setAction = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Type type = 2;
 * @return {!proto.calculator.Leg.Type}
 */
proto.calculator.Leg.prototype.getType = function() {
  return /** @type {!proto.calculator.Leg.Type} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.calculator.Leg.Type} value
 * @return {!proto.calculator.Leg} returns this
 */
proto.calculator.Leg.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional double strike = 3;
 * @return {number}
 */
proto.calculator.Leg.prototype.getStrike = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.Leg} returns this
 */
proto.calculator.Leg.prototype.setStrike = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double expiration_days = 4;
 * @return {number}
 */
proto.calculator.Leg.prototype.getExpirationDays = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.Leg} returns this
 */
proto.calculator.Leg.prototype.setExpirationDays = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int32 quantity = 5;
 * @return {number}
 */
proto.calculator.Leg.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.Leg} returns this
 */
proto.calculator.Leg.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.calculator.StrategyRequest.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.StrategyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.StrategyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.StrategyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.StrategyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
underlyingSymbol: jspb.Message.getFieldWithDefault(msg, 1, ""),
currentPrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
impliedVolatility: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
riskFreeRate: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
legsList: jspb.Message.toObjectList(msg.getLegsList(),
    proto.calculator.Leg.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.StrategyRequest}
 */
proto.calculator.StrategyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.StrategyRequest;
  return proto.calculator.StrategyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.StrategyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.StrategyRequest}
 */
proto.calculator.StrategyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUnderlyingSymbol(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCurrentPrice(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setImpliedVolatility(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRiskFreeRate(value);
      break;
    case 5:
      var value = new proto.calculator.Leg;
      reader.readMessage(value,proto.calculator.Leg.deserializeBinaryFromReader);
      msg.addLegs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.StrategyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.StrategyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.StrategyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.StrategyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUnderlyingSymbol();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCurrentPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getImpliedVolatility();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getRiskFreeRate();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getLegsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.calculator.Leg.serializeBinaryToWriter
    );
  }
};


/**
 * optional string underlying_symbol = 1;
 * @return {string}
 */
proto.calculator.StrategyRequest.prototype.getUnderlyingSymbol = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.calculator.StrategyRequest} returns this
 */
proto.calculator.StrategyRequest.prototype.setUnderlyingSymbol = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double current_price = 2;
 * @return {number}
 */
proto.calculator.StrategyRequest.prototype.getCurrentPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.StrategyRequest} returns this
 */
proto.calculator.StrategyRequest.prototype.setCurrentPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double implied_volatility = 3;
 * @return {number}
 */
proto.calculator.StrategyRequest.prototype.getImpliedVolatility = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.StrategyRequest} returns this
 */
proto.calculator.StrategyRequest.prototype.setImpliedVolatility = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double risk_free_rate = 4;
 * @return {number}
 */
proto.calculator.StrategyRequest.prototype.getRiskFreeRate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.StrategyRequest} returns this
 */
proto.calculator.StrategyRequest.prototype.setRiskFreeRate = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * repeated Leg legs = 5;
 * @return {!Array<!proto.calculator.Leg>}
 */
proto.calculator.StrategyRequest.prototype.getLegsList = function() {
  return /** @type{!Array<!proto.calculator.Leg>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.calculator.Leg, 5));
};


/**
 * @param {!Array<!proto.calculator.Leg>} value
 * @return {!proto.calculator.StrategyRequest} returns this
*/
proto.calculator.StrategyRequest.prototype.setLegsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.calculator.Leg=} opt_value
 * @param {number=} opt_index
 * @return {!proto.calculator.Leg}
 */
proto.calculator.StrategyRequest.prototype.addLegs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.calculator.Leg, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.calculator.StrategyRequest} returns this
 */
proto.calculator.StrategyRequest.prototype.clearLegsList = function() {
  return this.setLegsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.Greeks.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.Greeks.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.Greeks} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.Greeks.toObject = function(includeInstance, msg) {
  var f, obj = {
delta: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
gamma: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
theta: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
vega: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
rho: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.Greeks}
 */
proto.calculator.Greeks.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.Greeks;
  return proto.calculator.Greeks.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.Greeks} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.Greeks}
 */
proto.calculator.Greeks.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDelta(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setGamma(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTheta(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setVega(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setRho(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.Greeks.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.Greeks.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.Greeks} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.Greeks.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDelta();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getGamma();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getTheta();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getVega();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getRho();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
};


/**
 * optional double delta = 1;
 * @return {number}
 */
proto.calculator.Greeks.prototype.getDelta = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.Greeks} returns this
 */
proto.calculator.Greeks.prototype.setDelta = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double gamma = 2;
 * @return {number}
 */
proto.calculator.Greeks.prototype.getGamma = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.Greeks} returns this
 */
proto.calculator.Greeks.prototype.setGamma = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double theta = 3;
 * @return {number}
 */
proto.calculator.Greeks.prototype.getTheta = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.Greeks} returns this
 */
proto.calculator.Greeks.prototype.setTheta = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double vega = 4;
 * @return {number}
 */
proto.calculator.Greeks.prototype.getVega = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.Greeks} returns this
 */
proto.calculator.Greeks.prototype.setVega = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double rho = 5;
 * @return {number}
 */
proto.calculator.Greeks.prototype.getRho = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.Greeks} returns this
 */
proto.calculator.Greeks.prototype.setRho = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.PnLPoint.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.PnLPoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.PnLPoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.PnLPoint.toObject = function(includeInstance, msg) {
  var f, obj = {
underlyingPrice: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
pnl: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.PnLPoint}
 */
proto.calculator.PnLPoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.PnLPoint;
  return proto.calculator.PnLPoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.PnLPoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.PnLPoint}
 */
proto.calculator.PnLPoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setUnderlyingPrice(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPnl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.PnLPoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.PnLPoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.PnLPoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.PnLPoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUnderlyingPrice();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getPnl();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional double underlying_price = 1;
 * @return {number}
 */
proto.calculator.PnLPoint.prototype.getUnderlyingPrice = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.PnLPoint} returns this
 */
proto.calculator.PnLPoint.prototype.setUnderlyingPrice = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double pnl = 2;
 * @return {number}
 */
proto.calculator.PnLPoint.prototype.getPnl = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.PnLPoint} returns this
 */
proto.calculator.PnLPoint.prototype.setPnl = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.RiskMetrics.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.RiskMetrics.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.RiskMetrics} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.RiskMetrics.toObject = function(includeInstance, msg) {
  var f, obj = {
varParametric95: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
varParametric99: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
cvarParametric95: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
cvarParametric99: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.RiskMetrics}
 */
proto.calculator.RiskMetrics.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.RiskMetrics;
  return proto.calculator.RiskMetrics.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.RiskMetrics} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.RiskMetrics}
 */
proto.calculator.RiskMetrics.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setVarParametric95(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setVarParametric99(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCvarParametric95(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCvarParametric99(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.RiskMetrics.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.RiskMetrics.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.RiskMetrics} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.RiskMetrics.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVarParametric95();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getVarParametric99();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getCvarParametric95();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getCvarParametric99();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * optional double var_parametric_95 = 1;
 * @return {number}
 */
proto.calculator.RiskMetrics.prototype.getVarParametric95 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.RiskMetrics} returns this
 */
proto.calculator.RiskMetrics.prototype.setVarParametric95 = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double var_parametric_99 = 2;
 * @return {number}
 */
proto.calculator.RiskMetrics.prototype.getVarParametric99 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.RiskMetrics} returns this
 */
proto.calculator.RiskMetrics.prototype.setVarParametric99 = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double cvar_parametric_95 = 3;
 * @return {number}
 */
proto.calculator.RiskMetrics.prototype.getCvarParametric95 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.RiskMetrics} returns this
 */
proto.calculator.RiskMetrics.prototype.setCvarParametric95 = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double cvar_parametric_99 = 4;
 * @return {number}
 */
proto.calculator.RiskMetrics.prototype.getCvarParametric99 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.RiskMetrics} returns this
 */
proto.calculator.RiskMetrics.prototype.setCvarParametric99 = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.calculator.StrategyResponse.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.calculator.StrategyResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.calculator.StrategyResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.calculator.StrategyResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.StrategyResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
maxProfit: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
maxLoss: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
breakEven: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
expectedValue: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
pop: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
netGreeks: (f = msg.getNetGreeks()) && proto.calculator.Greeks.toObject(includeInstance, f),
riskMetrics: (f = msg.getRiskMetrics()) && proto.calculator.RiskMetrics.toObject(includeInstance, f),
pnlMatrixList: jspb.Message.toObjectList(msg.getPnlMatrixList(),
    proto.calculator.PnLPoint.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.calculator.StrategyResponse}
 */
proto.calculator.StrategyResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.calculator.StrategyResponse;
  return proto.calculator.StrategyResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.calculator.StrategyResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.calculator.StrategyResponse}
 */
proto.calculator.StrategyResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMaxProfit(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setMaxLoss(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setBreakEven(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setExpectedValue(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setPop(value);
      break;
    case 6:
      var value = new proto.calculator.Greeks;
      reader.readMessage(value,proto.calculator.Greeks.deserializeBinaryFromReader);
      msg.setNetGreeks(value);
      break;
    case 7:
      var value = new proto.calculator.RiskMetrics;
      reader.readMessage(value,proto.calculator.RiskMetrics.deserializeBinaryFromReader);
      msg.setRiskMetrics(value);
      break;
    case 8:
      var value = new proto.calculator.PnLPoint;
      reader.readMessage(value,proto.calculator.PnLPoint.deserializeBinaryFromReader);
      msg.addPnlMatrix(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.calculator.StrategyResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.calculator.StrategyResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.calculator.StrategyResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.calculator.StrategyResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMaxProfit();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getMaxLoss();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = message.getBreakEven();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = message.getExpectedValue();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getPop();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getNetGreeks();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.calculator.Greeks.serializeBinaryToWriter
    );
  }
  f = message.getRiskMetrics();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.calculator.RiskMetrics.serializeBinaryToWriter
    );
  }
  f = message.getPnlMatrixList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.calculator.PnLPoint.serializeBinaryToWriter
    );
  }
};


/**
 * optional double max_profit = 1;
 * @return {number}
 */
proto.calculator.StrategyResponse.prototype.getMaxProfit = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.StrategyResponse} returns this
 */
proto.calculator.StrategyResponse.prototype.setMaxProfit = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double max_loss = 2;
 * @return {number}
 */
proto.calculator.StrategyResponse.prototype.getMaxLoss = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.StrategyResponse} returns this
 */
proto.calculator.StrategyResponse.prototype.setMaxLoss = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional double break_even = 3;
 * @return {number}
 */
proto.calculator.StrategyResponse.prototype.getBreakEven = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.StrategyResponse} returns this
 */
proto.calculator.StrategyResponse.prototype.setBreakEven = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double expected_value = 4;
 * @return {number}
 */
proto.calculator.StrategyResponse.prototype.getExpectedValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.StrategyResponse} returns this
 */
proto.calculator.StrategyResponse.prototype.setExpectedValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double pop = 5;
 * @return {number}
 */
proto.calculator.StrategyResponse.prototype.getPop = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.calculator.StrategyResponse} returns this
 */
proto.calculator.StrategyResponse.prototype.setPop = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional Greeks net_greeks = 6;
 * @return {?proto.calculator.Greeks}
 */
proto.calculator.StrategyResponse.prototype.getNetGreeks = function() {
  return /** @type{?proto.calculator.Greeks} */ (
    jspb.Message.getWrapperField(this, proto.calculator.Greeks, 6));
};


/**
 * @param {?proto.calculator.Greeks|undefined} value
 * @return {!proto.calculator.StrategyResponse} returns this
*/
proto.calculator.StrategyResponse.prototype.setNetGreeks = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.calculator.StrategyResponse} returns this
 */
proto.calculator.StrategyResponse.prototype.clearNetGreeks = function() {
  return this.setNetGreeks(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.calculator.StrategyResponse.prototype.hasNetGreeks = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional RiskMetrics risk_metrics = 7;
 * @return {?proto.calculator.RiskMetrics}
 */
proto.calculator.StrategyResponse.prototype.getRiskMetrics = function() {
  return /** @type{?proto.calculator.RiskMetrics} */ (
    jspb.Message.getWrapperField(this, proto.calculator.RiskMetrics, 7));
};


/**
 * @param {?proto.calculator.RiskMetrics|undefined} value
 * @return {!proto.calculator.StrategyResponse} returns this
*/
proto.calculator.StrategyResponse.prototype.setRiskMetrics = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.calculator.StrategyResponse} returns this
 */
proto.calculator.StrategyResponse.prototype.clearRiskMetrics = function() {
  return this.setRiskMetrics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.calculator.StrategyResponse.prototype.hasRiskMetrics = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated PnLPoint pnl_matrix = 8;
 * @return {!Array<!proto.calculator.PnLPoint>}
 */
proto.calculator.StrategyResponse.prototype.getPnlMatrixList = function() {
  return /** @type{!Array<!proto.calculator.PnLPoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.calculator.PnLPoint, 8));
};


/**
 * @param {!Array<!proto.calculator.PnLPoint>} value
 * @return {!proto.calculator.StrategyResponse} returns this
*/
proto.calculator.StrategyResponse.prototype.setPnlMatrixList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.calculator.PnLPoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.calculator.PnLPoint}
 */
proto.calculator.StrategyResponse.prototype.addPnlMatrix = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.calculator.PnLPoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.calculator.StrategyResponse} returns this
 */
proto.calculator.StrategyResponse.prototype.clearPnlMatrixList = function() {
  return this.setPnlMatrixList([]);
};


goog.object.extend(exports, proto.calculator);
