/**
 * @fileoverview gRPC-Web generated client stub for sensen.finance
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.19.1
// source: finance.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as finance_pb from './finance_pb'; // proto import: "finance.proto"


export class FinanceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorComputePayment = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputePayment',
    grpcWeb.MethodType.UNARY,
    finance_pb.PaymentRequest,
    finance_pb.DecimalResponse,
    (request: finance_pb.PaymentRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DecimalResponse.deserializeBinary
  );

  computePayment(
    request: finance_pb.PaymentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DecimalResponse>;

  computePayment(
    request: finance_pb.PaymentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DecimalResponse>;

  computePayment(
    request: finance_pb.PaymentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputePayment',
        request,
        metadata || {},
        this.methodDescriptorComputePayment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputePayment',
    request,
    metadata || {},
    this.methodDescriptorComputePayment);
  }

  methodDescriptorComputePresentValue = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputePresentValue',
    grpcWeb.MethodType.UNARY,
    finance_pb.PresentValueRequest,
    finance_pb.DecimalResponse,
    (request: finance_pb.PresentValueRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DecimalResponse.deserializeBinary
  );

  computePresentValue(
    request: finance_pb.PresentValueRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DecimalResponse>;

  computePresentValue(
    request: finance_pb.PresentValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DecimalResponse>;

  computePresentValue(
    request: finance_pb.PresentValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputePresentValue',
        request,
        metadata || {},
        this.methodDescriptorComputePresentValue,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputePresentValue',
    request,
    metadata || {},
    this.methodDescriptorComputePresentValue);
  }

  methodDescriptorComputeFutureValue = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeFutureValue',
    grpcWeb.MethodType.UNARY,
    finance_pb.FutureValueRequest,
    finance_pb.DecimalResponse,
    (request: finance_pb.FutureValueRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DecimalResponse.deserializeBinary
  );

  computeFutureValue(
    request: finance_pb.FutureValueRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DecimalResponse>;

  computeFutureValue(
    request: finance_pb.FutureValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DecimalResponse>;

  computeFutureValue(
    request: finance_pb.FutureValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeFutureValue',
        request,
        metadata || {},
        this.methodDescriptorComputeFutureValue,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeFutureValue',
    request,
    metadata || {},
    this.methodDescriptorComputeFutureValue);
  }

  methodDescriptorComputeFutureValueDetailed = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeFutureValueDetailed',
    grpcWeb.MethodType.UNARY,
    finance_pb.FutureValueDetailedRequest,
    finance_pb.FutureValueDetailedResponse,
    (request: finance_pb.FutureValueDetailedRequest) => {
      return request.serializeBinary();
    },
    finance_pb.FutureValueDetailedResponse.deserializeBinary
  );

  computeFutureValueDetailed(
    request: finance_pb.FutureValueDetailedRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.FutureValueDetailedResponse>;

  computeFutureValueDetailed(
    request: finance_pb.FutureValueDetailedRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.FutureValueDetailedResponse) => void): grpcWeb.ClientReadableStream<finance_pb.FutureValueDetailedResponse>;

  computeFutureValueDetailed(
    request: finance_pb.FutureValueDetailedRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.FutureValueDetailedResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeFutureValueDetailed',
        request,
        metadata || {},
        this.methodDescriptorComputeFutureValueDetailed,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeFutureValueDetailed',
    request,
    metadata || {},
    this.methodDescriptorComputeFutureValueDetailed);
  }

  methodDescriptorComputeInterestPayment = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeInterestPayment',
    grpcWeb.MethodType.UNARY,
    finance_pb.PeriodPaymentRequest,
    finance_pb.DecimalResponse,
    (request: finance_pb.PeriodPaymentRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DecimalResponse.deserializeBinary
  );

  computeInterestPayment(
    request: finance_pb.PeriodPaymentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DecimalResponse>;

  computeInterestPayment(
    request: finance_pb.PeriodPaymentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DecimalResponse>;

  computeInterestPayment(
    request: finance_pb.PeriodPaymentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeInterestPayment',
        request,
        metadata || {},
        this.methodDescriptorComputeInterestPayment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeInterestPayment',
    request,
    metadata || {},
    this.methodDescriptorComputeInterestPayment);
  }

  methodDescriptorComputePrincipalPayment = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputePrincipalPayment',
    grpcWeb.MethodType.UNARY,
    finance_pb.PeriodPaymentRequest,
    finance_pb.DecimalResponse,
    (request: finance_pb.PeriodPaymentRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DecimalResponse.deserializeBinary
  );

  computePrincipalPayment(
    request: finance_pb.PeriodPaymentRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DecimalResponse>;

  computePrincipalPayment(
    request: finance_pb.PeriodPaymentRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DecimalResponse>;

  computePrincipalPayment(
    request: finance_pb.PeriodPaymentRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputePrincipalPayment',
        request,
        metadata || {},
        this.methodDescriptorComputePrincipalPayment,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputePrincipalPayment',
    request,
    metadata || {},
    this.methodDescriptorComputePrincipalPayment);
  }

  methodDescriptorComputeRate = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeRate',
    grpcWeb.MethodType.UNARY,
    finance_pb.RateRequest,
    finance_pb.DecimalResponse,
    (request: finance_pb.RateRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DecimalResponse.deserializeBinary
  );

  computeRate(
    request: finance_pb.RateRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DecimalResponse>;

  computeRate(
    request: finance_pb.RateRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DecimalResponse>;

  computeRate(
    request: finance_pb.RateRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeRate',
        request,
        metadata || {},
        this.methodDescriptorComputeRate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeRate',
    request,
    metadata || {},
    this.methodDescriptorComputeRate);
  }

  methodDescriptorComputePeriods = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputePeriods',
    grpcWeb.MethodType.UNARY,
    finance_pb.PeriodsRequest,
    finance_pb.DecimalResponse,
    (request: finance_pb.PeriodsRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DecimalResponse.deserializeBinary
  );

  computePeriods(
    request: finance_pb.PeriodsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DecimalResponse>;

  computePeriods(
    request: finance_pb.PeriodsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DecimalResponse>;

  computePeriods(
    request: finance_pb.PeriodsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DecimalResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputePeriods',
        request,
        metadata || {},
        this.methodDescriptorComputePeriods,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputePeriods',
    request,
    metadata || {},
    this.methodDescriptorComputePeriods);
  }

  methodDescriptorConvertInterestRate = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ConvertInterestRate',
    grpcWeb.MethodType.UNARY,
    finance_pb.RateConversionRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.RateConversionRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  convertInterestRate(
    request: finance_pb.RateConversionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  convertInterestRate(
    request: finance_pb.RateConversionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  convertInterestRate(
    request: finance_pb.RateConversionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ConvertInterestRate',
        request,
        metadata || {},
        this.methodDescriptorConvertInterestRate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ConvertInterestRate',
    request,
    metadata || {},
    this.methodDescriptorConvertInterestRate);
  }

  methodDescriptorComputeFisherRate = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeFisherRate',
    grpcWeb.MethodType.UNARY,
    finance_pb.FisherRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.FisherRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computeFisherRate(
    request: finance_pb.FisherRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computeFisherRate(
    request: finance_pb.FisherRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computeFisherRate(
    request: finance_pb.FisherRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeFisherRate',
        request,
        metadata || {},
        this.methodDescriptorComputeFisherRate,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeFisherRate',
    request,
    metadata || {},
    this.methodDescriptorComputeFisherRate);
  }

  methodDescriptorComputeAmortization = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeAmortization',
    grpcWeb.MethodType.UNARY,
    finance_pb.AmortizationRequest,
    finance_pb.AmortizationResponse,
    (request: finance_pb.AmortizationRequest) => {
      return request.serializeBinary();
    },
    finance_pb.AmortizationResponse.deserializeBinary
  );

  computeAmortization(
    request: finance_pb.AmortizationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.AmortizationResponse>;

  computeAmortization(
    request: finance_pb.AmortizationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.AmortizationResponse) => void): grpcWeb.ClientReadableStream<finance_pb.AmortizationResponse>;

  computeAmortization(
    request: finance_pb.AmortizationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.AmortizationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeAmortization',
        request,
        metadata || {},
        this.methodDescriptorComputeAmortization,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeAmortization',
    request,
    metadata || {},
    this.methodDescriptorComputeAmortization);
  }

  methodDescriptorComputeDetailedAmortization = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeDetailedAmortization',
    grpcWeb.MethodType.UNARY,
    finance_pb.DetailedAmortizationRequest,
    finance_pb.DetailedAmortizationResponse,
    (request: finance_pb.DetailedAmortizationRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DetailedAmortizationResponse.deserializeBinary
  );

  computeDetailedAmortization(
    request: finance_pb.DetailedAmortizationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DetailedAmortizationResponse>;

  computeDetailedAmortization(
    request: finance_pb.DetailedAmortizationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DetailedAmortizationResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DetailedAmortizationResponse>;

  computeDetailedAmortization(
    request: finance_pb.DetailedAmortizationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DetailedAmortizationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeDetailedAmortization',
        request,
        metadata || {},
        this.methodDescriptorComputeDetailedAmortization,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeDetailedAmortization',
    request,
    metadata || {},
    this.methodDescriptorComputeDetailedAmortization);
  }

  methodDescriptorComputeAmortizationBatch = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeAmortizationBatch',
    grpcWeb.MethodType.UNARY,
    finance_pb.AmortizationBatchRequest,
    finance_pb.AmortizationBatchResponse,
    (request: finance_pb.AmortizationBatchRequest) => {
      return request.serializeBinary();
    },
    finance_pb.AmortizationBatchResponse.deserializeBinary
  );

  computeAmortizationBatch(
    request: finance_pb.AmortizationBatchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.AmortizationBatchResponse>;

  computeAmortizationBatch(
    request: finance_pb.AmortizationBatchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.AmortizationBatchResponse) => void): grpcWeb.ClientReadableStream<finance_pb.AmortizationBatchResponse>;

  computeAmortizationBatch(
    request: finance_pb.AmortizationBatchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.AmortizationBatchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeAmortizationBatch',
        request,
        metadata || {},
        this.methodDescriptorComputeAmortizationBatch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeAmortizationBatch',
    request,
    metadata || {},
    this.methodDescriptorComputeAmortizationBatch);
  }

  methodDescriptorComputeHeloc = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeHeloc',
    grpcWeb.MethodType.UNARY,
    finance_pb.HelocRequest,
    finance_pb.HelocResponse,
    (request: finance_pb.HelocRequest) => {
      return request.serializeBinary();
    },
    finance_pb.HelocResponse.deserializeBinary
  );

  computeHeloc(
    request: finance_pb.HelocRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.HelocResponse>;

  computeHeloc(
    request: finance_pb.HelocRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.HelocResponse) => void): grpcWeb.ClientReadableStream<finance_pb.HelocResponse>;

  computeHeloc(
    request: finance_pb.HelocRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.HelocResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeHeloc',
        request,
        metadata || {},
        this.methodDescriptorComputeHeloc,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeHeloc',
    request,
    metadata || {},
    this.methodDescriptorComputeHeloc);
  }

  methodDescriptorComputeRefinance = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeRefinance',
    grpcWeb.MethodType.UNARY,
    finance_pb.RefinanceRequest,
    finance_pb.RefinanceResponse,
    (request: finance_pb.RefinanceRequest) => {
      return request.serializeBinary();
    },
    finance_pb.RefinanceResponse.deserializeBinary
  );

  computeRefinance(
    request: finance_pb.RefinanceRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.RefinanceResponse>;

  computeRefinance(
    request: finance_pb.RefinanceRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.RefinanceResponse) => void): grpcWeb.ClientReadableStream<finance_pb.RefinanceResponse>;

  computeRefinance(
    request: finance_pb.RefinanceRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.RefinanceResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeRefinance',
        request,
        metadata || {},
        this.methodDescriptorComputeRefinance,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeRefinance',
    request,
    metadata || {},
    this.methodDescriptorComputeRefinance);
  }

  methodDescriptorComputePayoffTiming = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputePayoffTiming',
    grpcWeb.MethodType.UNARY,
    finance_pb.PayoffTimingRequest,
    finance_pb.PayoffTimingResponse,
    (request: finance_pb.PayoffTimingRequest) => {
      return request.serializeBinary();
    },
    finance_pb.PayoffTimingResponse.deserializeBinary
  );

  computePayoffTiming(
    request: finance_pb.PayoffTimingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.PayoffTimingResponse>;

  computePayoffTiming(
    request: finance_pb.PayoffTimingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.PayoffTimingResponse) => void): grpcWeb.ClientReadableStream<finance_pb.PayoffTimingResponse>;

  computePayoffTiming(
    request: finance_pb.PayoffTimingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.PayoffTimingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputePayoffTiming',
        request,
        metadata || {},
        this.methodDescriptorComputePayoffTiming,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputePayoffTiming',
    request,
    metadata || {},
    this.methodDescriptorComputePayoffTiming);
  }

  methodDescriptorComputeMortgageRecast = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeMortgageRecast',
    grpcWeb.MethodType.UNARY,
    finance_pb.MortgageRecastRequest,
    finance_pb.MortgageRecastResponse,
    (request: finance_pb.MortgageRecastRequest) => {
      return request.serializeBinary();
    },
    finance_pb.MortgageRecastResponse.deserializeBinary
  );

  computeMortgageRecast(
    request: finance_pb.MortgageRecastRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.MortgageRecastResponse>;

  computeMortgageRecast(
    request: finance_pb.MortgageRecastRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.MortgageRecastResponse) => void): grpcWeb.ClientReadableStream<finance_pb.MortgageRecastResponse>;

  computeMortgageRecast(
    request: finance_pb.MortgageRecastRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.MortgageRecastResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeMortgageRecast',
        request,
        metadata || {},
        this.methodDescriptorComputeMortgageRecast,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeMortgageRecast',
    request,
    metadata || {},
    this.methodDescriptorComputeMortgageRecast);
  }

  methodDescriptorComputeNpv = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeNpv',
    grpcWeb.MethodType.UNARY,
    finance_pb.NpvRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.NpvRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computeNpv(
    request: finance_pb.NpvRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computeNpv(
    request: finance_pb.NpvRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computeNpv(
    request: finance_pb.NpvRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeNpv',
        request,
        metadata || {},
        this.methodDescriptorComputeNpv,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeNpv',
    request,
    metadata || {},
    this.methodDescriptorComputeNpv);
  }

  methodDescriptorComputeIrr = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeIrr',
    grpcWeb.MethodType.UNARY,
    finance_pb.IrrRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.IrrRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computeIrr(
    request: finance_pb.IrrRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computeIrr(
    request: finance_pb.IrrRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computeIrr(
    request: finance_pb.IrrRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeIrr',
        request,
        metadata || {},
        this.methodDescriptorComputeIrr,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeIrr',
    request,
    metadata || {},
    this.methodDescriptorComputeIrr);
  }

  methodDescriptorComputeXnpv = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeXnpv',
    grpcWeb.MethodType.UNARY,
    finance_pb.DatedCashFlowRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.DatedCashFlowRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computeXnpv(
    request: finance_pb.DatedCashFlowRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computeXnpv(
    request: finance_pb.DatedCashFlowRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computeXnpv(
    request: finance_pb.DatedCashFlowRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeXnpv',
        request,
        metadata || {},
        this.methodDescriptorComputeXnpv,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeXnpv',
    request,
    metadata || {},
    this.methodDescriptorComputeXnpv);
  }

  methodDescriptorComputeXirr = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeXirr',
    grpcWeb.MethodType.UNARY,
    finance_pb.DatedCashFlowRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.DatedCashFlowRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computeXirr(
    request: finance_pb.DatedCashFlowRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computeXirr(
    request: finance_pb.DatedCashFlowRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computeXirr(
    request: finance_pb.DatedCashFlowRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeXirr',
        request,
        metadata || {},
        this.methodDescriptorComputeXirr,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeXirr',
    request,
    metadata || {},
    this.methodDescriptorComputeXirr);
  }

  methodDescriptorComputePaybackPeriod = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputePaybackPeriod',
    grpcWeb.MethodType.UNARY,
    finance_pb.PaybackRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.PaybackRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computePaybackPeriod(
    request: finance_pb.PaybackRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computePaybackPeriod(
    request: finance_pb.PaybackRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computePaybackPeriod(
    request: finance_pb.PaybackRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputePaybackPeriod',
        request,
        metadata || {},
        this.methodDescriptorComputePaybackPeriod,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputePaybackPeriod',
    request,
    metadata || {},
    this.methodDescriptorComputePaybackPeriod);
  }

  methodDescriptorComputeCumulative = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeCumulative',
    grpcWeb.MethodType.UNARY,
    finance_pb.CumulativeRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.CumulativeRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computeCumulative(
    request: finance_pb.CumulativeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computeCumulative(
    request: finance_pb.CumulativeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computeCumulative(
    request: finance_pb.CumulativeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeCumulative',
        request,
        metadata || {},
        this.methodDescriptorComputeCumulative,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeCumulative',
    request,
    metadata || {},
    this.methodDescriptorComputeCumulative);
  }

  methodDescriptorComputeDepreciation = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeDepreciation',
    grpcWeb.MethodType.UNARY,
    finance_pb.DepreciationRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.DepreciationRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computeDepreciation(
    request: finance_pb.DepreciationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computeDepreciation(
    request: finance_pb.DepreciationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computeDepreciation(
    request: finance_pb.DepreciationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeDepreciation',
        request,
        metadata || {},
        this.methodDescriptorComputeDepreciation,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeDepreciation',
    request,
    metadata || {},
    this.methodDescriptorComputeDepreciation);
  }

  methodDescriptorAnalyzeBond = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/AnalyzeBond',
    grpcWeb.MethodType.UNARY,
    finance_pb.BondRequest,
    finance_pb.BondResponse,
    (request: finance_pb.BondRequest) => {
      return request.serializeBinary();
    },
    finance_pb.BondResponse.deserializeBinary
  );

  analyzeBond(
    request: finance_pb.BondRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.BondResponse>;

  analyzeBond(
    request: finance_pb.BondRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.BondResponse) => void): grpcWeb.ClientReadableStream<finance_pb.BondResponse>;

  analyzeBond(
    request: finance_pb.BondRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.BondResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/AnalyzeBond',
        request,
        metadata || {},
        this.methodDescriptorAnalyzeBond,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/AnalyzeBond',
    request,
    metadata || {},
    this.methodDescriptorAnalyzeBond);
  }

  methodDescriptorAnalyzeTreasuryBill = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/AnalyzeTreasuryBill',
    grpcWeb.MethodType.UNARY,
    finance_pb.TreasuryBillRequest,
    finance_pb.TreasuryBillResponse,
    (request: finance_pb.TreasuryBillRequest) => {
      return request.serializeBinary();
    },
    finance_pb.TreasuryBillResponse.deserializeBinary
  );

  analyzeTreasuryBill(
    request: finance_pb.TreasuryBillRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.TreasuryBillResponse>;

  analyzeTreasuryBill(
    request: finance_pb.TreasuryBillRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.TreasuryBillResponse) => void): grpcWeb.ClientReadableStream<finance_pb.TreasuryBillResponse>;

  analyzeTreasuryBill(
    request: finance_pb.TreasuryBillRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.TreasuryBillResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/AnalyzeTreasuryBill',
        request,
        metadata || {},
        this.methodDescriptorAnalyzeTreasuryBill,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/AnalyzeTreasuryBill',
    request,
    metadata || {},
    this.methodDescriptorAnalyzeTreasuryBill);
  }

  methodDescriptorPriceFutures = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/PriceFutures',
    grpcWeb.MethodType.UNARY,
    finance_pb.FuturesPricingRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.FuturesPricingRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  priceFutures(
    request: finance_pb.FuturesPricingRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  priceFutures(
    request: finance_pb.FuturesPricingRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  priceFutures(
    request: finance_pb.FuturesPricingRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/PriceFutures',
        request,
        metadata || {},
        this.methodDescriptorPriceFutures,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/PriceFutures',
    request,
    metadata || {},
    this.methodDescriptorPriceFutures);
  }

  methodDescriptorValueFutures = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ValueFutures',
    grpcWeb.MethodType.UNARY,
    finance_pb.FuturesValuationRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.FuturesValuationRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  valueFutures(
    request: finance_pb.FuturesValuationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  valueFutures(
    request: finance_pb.FuturesValuationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  valueFutures(
    request: finance_pb.FuturesValuationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ValueFutures',
        request,
        metadata || {},
        this.methodDescriptorValueFutures,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ValueFutures',
    request,
    metadata || {},
    this.methodDescriptorValueFutures);
  }

  methodDescriptorSimulateMarginAccount = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/SimulateMarginAccount',
    grpcWeb.MethodType.UNARY,
    finance_pb.MarginSimulationRequest,
    finance_pb.MarginSimulationResponse,
    (request: finance_pb.MarginSimulationRequest) => {
      return request.serializeBinary();
    },
    finance_pb.MarginSimulationResponse.deserializeBinary
  );

  simulateMarginAccount(
    request: finance_pb.MarginSimulationRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.MarginSimulationResponse>;

  simulateMarginAccount(
    request: finance_pb.MarginSimulationRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.MarginSimulationResponse) => void): grpcWeb.ClientReadableStream<finance_pb.MarginSimulationResponse>;

  simulateMarginAccount(
    request: finance_pb.MarginSimulationRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.MarginSimulationResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/SimulateMarginAccount',
        request,
        metadata || {},
        this.methodDescriptorSimulateMarginAccount,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/SimulateMarginAccount',
    request,
    metadata || {},
    this.methodDescriptorSimulateMarginAccount);
  }

  methodDescriptorComputeHedge = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeHedge',
    grpcWeb.MethodType.UNARY,
    finance_pb.HedgeRequest,
    finance_pb.HedgeResponse,
    (request: finance_pb.HedgeRequest) => {
      return request.serializeBinary();
    },
    finance_pb.HedgeResponse.deserializeBinary
  );

  computeHedge(
    request: finance_pb.HedgeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.HedgeResponse>;

  computeHedge(
    request: finance_pb.HedgeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.HedgeResponse) => void): grpcWeb.ClientReadableStream<finance_pb.HedgeResponse>;

  computeHedge(
    request: finance_pb.HedgeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.HedgeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeHedge',
        request,
        metadata || {},
        this.methodDescriptorComputeHedge,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeHedge',
    request,
    metadata || {},
    this.methodDescriptorComputeHedge);
  }

  methodDescriptorComputeCommoditySpread = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeCommoditySpread',
    grpcWeb.MethodType.UNARY,
    finance_pb.CommoditySpreadRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.CommoditySpreadRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  computeCommoditySpread(
    request: finance_pb.CommoditySpreadRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  computeCommoditySpread(
    request: finance_pb.CommoditySpreadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  computeCommoditySpread(
    request: finance_pb.CommoditySpreadRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeCommoditySpread',
        request,
        metadata || {},
        this.methodDescriptorComputeCommoditySpread,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeCommoditySpread',
    request,
    metadata || {},
    this.methodDescriptorComputeCommoditySpread);
  }

  methodDescriptorComputeRentalRoi = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeRentalRoi',
    grpcWeb.MethodType.UNARY,
    finance_pb.RentalRoiRequest,
    finance_pb.RentalRoiResponse,
    (request: finance_pb.RentalRoiRequest) => {
      return request.serializeBinary();
    },
    finance_pb.RentalRoiResponse.deserializeBinary
  );

  computeRentalRoi(
    request: finance_pb.RentalRoiRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.RentalRoiResponse>;

  computeRentalRoi(
    request: finance_pb.RentalRoiRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.RentalRoiResponse) => void): grpcWeb.ClientReadableStream<finance_pb.RentalRoiResponse>;

  computeRentalRoi(
    request: finance_pb.RentalRoiRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.RentalRoiResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeRentalRoi',
        request,
        metadata || {},
        this.methodDescriptorComputeRentalRoi,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeRentalRoi',
    request,
    metadata || {},
    this.methodDescriptorComputeRentalRoi);
  }

  methodDescriptorComputeHomeFutureValue = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeHomeFutureValue',
    grpcWeb.MethodType.UNARY,
    finance_pb.HomeFutureValueRequest,
    finance_pb.HomeFutureValueResponse,
    (request: finance_pb.HomeFutureValueRequest) => {
      return request.serializeBinary();
    },
    finance_pb.HomeFutureValueResponse.deserializeBinary
  );

  computeHomeFutureValue(
    request: finance_pb.HomeFutureValueRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.HomeFutureValueResponse>;

  computeHomeFutureValue(
    request: finance_pb.HomeFutureValueRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.HomeFutureValueResponse) => void): grpcWeb.ClientReadableStream<finance_pb.HomeFutureValueResponse>;

  computeHomeFutureValue(
    request: finance_pb.HomeFutureValueRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.HomeFutureValueResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeHomeFutureValue',
        request,
        metadata || {},
        this.methodDescriptorComputeHomeFutureValue,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeHomeFutureValue',
    request,
    metadata || {},
    this.methodDescriptorComputeHomeFutureValue);
  }

  methodDescriptorComputeRentVsBuy = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeRentVsBuy',
    grpcWeb.MethodType.UNARY,
    finance_pb.RentVsBuyRequest,
    finance_pb.RentVsBuyResponse,
    (request: finance_pb.RentVsBuyRequest) => {
      return request.serializeBinary();
    },
    finance_pb.RentVsBuyResponse.deserializeBinary
  );

  computeRentVsBuy(
    request: finance_pb.RentVsBuyRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.RentVsBuyResponse>;

  computeRentVsBuy(
    request: finance_pb.RentVsBuyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.RentVsBuyResponse) => void): grpcWeb.ClientReadableStream<finance_pb.RentVsBuyResponse>;

  computeRentVsBuy(
    request: finance_pb.RentVsBuyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.RentVsBuyResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeRentVsBuy',
        request,
        metadata || {},
        this.methodDescriptorComputeRentVsBuy,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeRentVsBuy',
    request,
    metadata || {},
    this.methodDescriptorComputeRentVsBuy);
  }

  methodDescriptorComputeRentVsBuyBatch = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeRentVsBuyBatch',
    grpcWeb.MethodType.UNARY,
    finance_pb.RentVsBuyBatchRequest,
    finance_pb.RentVsBuyBatchResponse,
    (request: finance_pb.RentVsBuyBatchRequest) => {
      return request.serializeBinary();
    },
    finance_pb.RentVsBuyBatchResponse.deserializeBinary
  );

  computeRentVsBuyBatch(
    request: finance_pb.RentVsBuyBatchRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.RentVsBuyBatchResponse>;

  computeRentVsBuyBatch(
    request: finance_pb.RentVsBuyBatchRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.RentVsBuyBatchResponse) => void): grpcWeb.ClientReadableStream<finance_pb.RentVsBuyBatchResponse>;

  computeRentVsBuyBatch(
    request: finance_pb.RentVsBuyBatchRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.RentVsBuyBatchResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeRentVsBuyBatch',
        request,
        metadata || {},
        this.methodDescriptorComputeRentVsBuyBatch,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeRentVsBuyBatch',
    request,
    metadata || {},
    this.methodDescriptorComputeRentVsBuyBatch);
  }

  methodDescriptorComputeHomeNpv = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeHomeNpv',
    grpcWeb.MethodType.UNARY,
    finance_pb.HomeNpvRequest,
    finance_pb.HomeNpvResponse,
    (request: finance_pb.HomeNpvRequest) => {
      return request.serializeBinary();
    },
    finance_pb.HomeNpvResponse.deserializeBinary
  );

  computeHomeNpv(
    request: finance_pb.HomeNpvRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.HomeNpvResponse>;

  computeHomeNpv(
    request: finance_pb.HomeNpvRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.HomeNpvResponse) => void): grpcWeb.ClientReadableStream<finance_pb.HomeNpvResponse>;

  computeHomeNpv(
    request: finance_pb.HomeNpvRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.HomeNpvResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeHomeNpv',
        request,
        metadata || {},
        this.methodDescriptorComputeHomeNpv,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeHomeNpv',
    request,
    metadata || {},
    this.methodDescriptorComputeHomeNpv);
  }

  methodDescriptorComputeClosingCosts = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeClosingCosts',
    grpcWeb.MethodType.UNARY,
    finance_pb.ClosingCostsRequest,
    finance_pb.ClosingCostsResponse,
    (request: finance_pb.ClosingCostsRequest) => {
      return request.serializeBinary();
    },
    finance_pb.ClosingCostsResponse.deserializeBinary
  );

  computeClosingCosts(
    request: finance_pb.ClosingCostsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.ClosingCostsResponse>;

  computeClosingCosts(
    request: finance_pb.ClosingCostsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.ClosingCostsResponse) => void): grpcWeb.ClientReadableStream<finance_pb.ClosingCostsResponse>;

  computeClosingCosts(
    request: finance_pb.ClosingCostsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.ClosingCostsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeClosingCosts',
        request,
        metadata || {},
        this.methodDescriptorComputeClosingCosts,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeClosingCosts',
    request,
    metadata || {},
    this.methodDescriptorComputeClosingCosts);
  }

  methodDescriptorRefreshStateAssumptions = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/RefreshStateAssumptions',
    grpcWeb.MethodType.UNARY,
    finance_pb.RefreshStateAssumptionsRequest,
    finance_pb.RefreshStateAssumptionsResponse,
    (request: finance_pb.RefreshStateAssumptionsRequest) => {
      return request.serializeBinary();
    },
    finance_pb.RefreshStateAssumptionsResponse.deserializeBinary
  );

  refreshStateAssumptions(
    request: finance_pb.RefreshStateAssumptionsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.RefreshStateAssumptionsResponse>;

  refreshStateAssumptions(
    request: finance_pb.RefreshStateAssumptionsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.RefreshStateAssumptionsResponse) => void): grpcWeb.ClientReadableStream<finance_pb.RefreshStateAssumptionsResponse>;

  refreshStateAssumptions(
    request: finance_pb.RefreshStateAssumptionsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.RefreshStateAssumptionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/RefreshStateAssumptions',
        request,
        metadata || {},
        this.methodDescriptorRefreshStateAssumptions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/RefreshStateAssumptions',
    request,
    metadata || {},
    this.methodDescriptorRefreshStateAssumptions);
  }

  methodDescriptorGetStateAssumptions = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/GetStateAssumptions',
    grpcWeb.MethodType.UNARY,
    finance_pb.GetStateAssumptionsRequest,
    finance_pb.GetStateAssumptionsResponse,
    (request: finance_pb.GetStateAssumptionsRequest) => {
      return request.serializeBinary();
    },
    finance_pb.GetStateAssumptionsResponse.deserializeBinary
  );

  getStateAssumptions(
    request: finance_pb.GetStateAssumptionsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.GetStateAssumptionsResponse>;

  getStateAssumptions(
    request: finance_pb.GetStateAssumptionsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.GetStateAssumptionsResponse) => void): grpcWeb.ClientReadableStream<finance_pb.GetStateAssumptionsResponse>;

  getStateAssumptions(
    request: finance_pb.GetStateAssumptionsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.GetStateAssumptionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/GetStateAssumptions',
        request,
        metadata || {},
        this.methodDescriptorGetStateAssumptions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/GetStateAssumptions',
    request,
    metadata || {},
    this.methodDescriptorGetStateAssumptions);
  }

  methodDescriptorPriceOptionTree = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/PriceOptionTree',
    grpcWeb.MethodType.UNARY,
    finance_pb.OptionTreeRequest,
    finance_pb.OptionPricingResponse,
    (request: finance_pb.OptionTreeRequest) => {
      return request.serializeBinary();
    },
    finance_pb.OptionPricingResponse.deserializeBinary
  );

  priceOptionTree(
    request: finance_pb.OptionTreeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.OptionPricingResponse>;

  priceOptionTree(
    request: finance_pb.OptionTreeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.OptionPricingResponse) => void): grpcWeb.ClientReadableStream<finance_pb.OptionPricingResponse>;

  priceOptionTree(
    request: finance_pb.OptionTreeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.OptionPricingResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/PriceOptionTree',
        request,
        metadata || {},
        this.methodDescriptorPriceOptionTree,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/PriceOptionTree',
    request,
    metadata || {},
    this.methodDescriptorPriceOptionTree);
  }

  methodDescriptorPriceBlackScholes = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/PriceBlackScholes',
    grpcWeb.MethodType.UNARY,
    finance_pb.BlackScholesRequest,
    finance_pb.BlackScholesResponse,
    (request: finance_pb.BlackScholesRequest) => {
      return request.serializeBinary();
    },
    finance_pb.BlackScholesResponse.deserializeBinary
  );

  priceBlackScholes(
    request: finance_pb.BlackScholesRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.BlackScholesResponse>;

  priceBlackScholes(
    request: finance_pb.BlackScholesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.BlackScholesResponse) => void): grpcWeb.ClientReadableStream<finance_pb.BlackScholesResponse>;

  priceBlackScholes(
    request: finance_pb.BlackScholesRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.BlackScholesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/PriceBlackScholes',
        request,
        metadata || {},
        this.methodDescriptorPriceBlackScholes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/PriceBlackScholes',
    request,
    metadata || {},
    this.methodDescriptorPriceBlackScholes);
  }

  methodDescriptorPriceOptionMonteCarlo = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/PriceOptionMonteCarlo',
    grpcWeb.MethodType.UNARY,
    finance_pb.MonteCarloRequest,
    finance_pb.DoubleResponse,
    (request: finance_pb.MonteCarloRequest) => {
      return request.serializeBinary();
    },
    finance_pb.DoubleResponse.deserializeBinary
  );

  priceOptionMonteCarlo(
    request: finance_pb.MonteCarloRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.DoubleResponse>;

  priceOptionMonteCarlo(
    request: finance_pb.MonteCarloRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void): grpcWeb.ClientReadableStream<finance_pb.DoubleResponse>;

  priceOptionMonteCarlo(
    request: finance_pb.MonteCarloRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.DoubleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/PriceOptionMonteCarlo',
        request,
        metadata || {},
        this.methodDescriptorPriceOptionMonteCarlo,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/PriceOptionMonteCarlo',
    request,
    metadata || {},
    this.methodDescriptorPriceOptionMonteCarlo);
  }

  methodDescriptorComputeProbabilityTree = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeProbabilityTree',
    grpcWeb.MethodType.UNARY,
    finance_pb.ProbabilityTreeRequest,
    finance_pb.ProbabilityTreeResponse,
    (request: finance_pb.ProbabilityTreeRequest) => {
      return request.serializeBinary();
    },
    finance_pb.ProbabilityTreeResponse.deserializeBinary
  );

  computeProbabilityTree(
    request: finance_pb.ProbabilityTreeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.ProbabilityTreeResponse>;

  computeProbabilityTree(
    request: finance_pb.ProbabilityTreeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.ProbabilityTreeResponse) => void): grpcWeb.ClientReadableStream<finance_pb.ProbabilityTreeResponse>;

  computeProbabilityTree(
    request: finance_pb.ProbabilityTreeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.ProbabilityTreeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeProbabilityTree',
        request,
        metadata || {},
        this.methodDescriptorComputeProbabilityTree,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeProbabilityTree',
    request,
    metadata || {},
    this.methodDescriptorComputeProbabilityTree);
  }

  methodDescriptorComputePortfolioStats = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputePortfolioStats',
    grpcWeb.MethodType.UNARY,
    finance_pb.PortfolioStatsRequest,
    finance_pb.PortfolioStatsResponse,
    (request: finance_pb.PortfolioStatsRequest) => {
      return request.serializeBinary();
    },
    finance_pb.PortfolioStatsResponse.deserializeBinary
  );

  computePortfolioStats(
    request: finance_pb.PortfolioStatsRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.PortfolioStatsResponse>;

  computePortfolioStats(
    request: finance_pb.PortfolioStatsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.PortfolioStatsResponse) => void): grpcWeb.ClientReadableStream<finance_pb.PortfolioStatsResponse>;

  computePortfolioStats(
    request: finance_pb.PortfolioStatsRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.PortfolioStatsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputePortfolioStats',
        request,
        metadata || {},
        this.methodDescriptorComputePortfolioStats,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputePortfolioStats',
    request,
    metadata || {},
    this.methodDescriptorComputePortfolioStats);
  }

  methodDescriptorOptimizePortfolio = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/OptimizePortfolio',
    grpcWeb.MethodType.UNARY,
    finance_pb.PortfolioOptimizeRequest,
    finance_pb.PortfolioOptimizeResponse,
    (request: finance_pb.PortfolioOptimizeRequest) => {
      return request.serializeBinary();
    },
    finance_pb.PortfolioOptimizeResponse.deserializeBinary
  );

  optimizePortfolio(
    request: finance_pb.PortfolioOptimizeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.PortfolioOptimizeResponse>;

  optimizePortfolio(
    request: finance_pb.PortfolioOptimizeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.PortfolioOptimizeResponse) => void): grpcWeb.ClientReadableStream<finance_pb.PortfolioOptimizeResponse>;

  optimizePortfolio(
    request: finance_pb.PortfolioOptimizeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.PortfolioOptimizeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/OptimizePortfolio',
        request,
        metadata || {},
        this.methodDescriptorOptimizePortfolio,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/OptimizePortfolio',
    request,
    metadata || {},
    this.methodDescriptorOptimizePortfolio);
  }

  methodDescriptorComputeRiskContributions = new grpcWeb.MethodDescriptor(
    '/sensen.finance.Finance/ComputeRiskContributions',
    grpcWeb.MethodType.UNARY,
    finance_pb.RiskContributionRequest,
    finance_pb.RiskContributionResponse,
    (request: finance_pb.RiskContributionRequest) => {
      return request.serializeBinary();
    },
    finance_pb.RiskContributionResponse.deserializeBinary
  );

  computeRiskContributions(
    request: finance_pb.RiskContributionRequest,
    metadata?: grpcWeb.Metadata | null): Promise<finance_pb.RiskContributionResponse>;

  computeRiskContributions(
    request: finance_pb.RiskContributionRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: finance_pb.RiskContributionResponse) => void): grpcWeb.ClientReadableStream<finance_pb.RiskContributionResponse>;

  computeRiskContributions(
    request: finance_pb.RiskContributionRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: finance_pb.RiskContributionResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/sensen.finance.Finance/ComputeRiskContributions',
        request,
        metadata || {},
        this.methodDescriptorComputeRiskContributions,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/sensen.finance.Finance/ComputeRiskContributions',
    request,
    metadata || {},
    this.methodDescriptorComputeRiskContributions);
  }

}

