#!/usr/bin/env bash
# Assert every copy of ToolchainBMIGuard.cmake is BYTE-IDENTICAL to this tree's.
#
# @author Olumuyiwa Oluwasanmi
#
# The guard is a shared build-system file copied into each TOP-LEVEL project in this
# ecosystem, because there is no single repository all of them descend from: OFC
# embeds sensen, sensen embeds tbqwf/SGEE/logger/fastjson, and tbqwf embeds two of
# those again. N copies with no mechanism is the `ALLOWED_OPERATIONS` defect -- a
# table maintained by hand in another repository that nothing here can even see.
#
# IDENTITY AGAINST THE SOURCE OF TRUTH, NOT A RECORDED CHECKSUM, and that is the same
# choice `check_vendored_protos.sh` made for the same reason: a recorded value must be
# regenerated by hand and the hand forgets. The consuming repository's own manifest
# went stale for a month and reported the CORRECT file as corrupt.
#
# POSITIVE CONTROL: comparing zero files is a FAILURE, not a pass.
set -uo pipefail
cd "$(dirname "$0")/.." || exit 9

REF=backend/cmake/ToolchainBMIGuard.cmake
[ -f "$REF" ] || { echo "FAIL: the reference copy $REF does not exist"; exit 1; }

# Only the copies THIS checkout can reach. tbqwf is deliberately not populated here
# (it opens the -maes/-mpclmul flag gate), so its copy is gated in its own repository
# rather than claimed here -- naming what a gate cannot see is half of its honesty.
CANDIDATES=(
  backend/sensen/cmake/ToolchainBMIGuard.cmake
  backend/external/SGEE/cmake/ToolchainBMIGuard.cmake
)

compared=0
bad=0
for c in "${CANDIDATES[@]}"; do
  if [ ! -f "$c" ]; then
    printf '  SKIP      %s (not populated in this checkout)\n' "$c"
    continue
  fi
  compared=$((compared+1))
  if cmp -s "$REF" "$c"; then
    printf '  IDENTICAL %s\n' "$c"
  else
    printf '  DIFFERS   %s\n' "$c"
    diff -u "$REF" "$c" | head -20
    bad=$((bad+1))
  fi
done

if [ "$compared" -eq 0 ]; then
  echo "FAIL: compared ZERO copies. A gate that examines nothing agrees with everything."
  exit 1
fi
if [ "$bad" -ne 0 ]; then
  echo "FAIL: $bad of $compared copies differ from $REF"
  exit 1
fi
echo "OK: $compared copy/copies byte-identical to $REF"
