#!/usr/bin/env bash
#
# The vendored client contracts must be BYTE-IDENTICAL to the authoritative ones.
#
# @author Olumuyiwa Oluwasanmi
#
# `clients/mortgagefv/proto/` is a COPY handed to the consuming site. Nothing
# derived it and nothing checked it, so on 2026-09-23 it still described money
# as "BigDecimal's own 18-decimal-place string" -- six days after the engine
# began emitting 38. The authoritative `backend/proto/` said 18 as well, so the
# two agreed with each other and both disagreed with the deployed engine.
#
# WHY BYTE-IDENTITY RATHER THAN A CHECKSUM MANIFEST. The consuming repository
# gates its own copy with a recorded sha256 (`clients/mortgagefv/proto/
# CHECKSUMS.txt` + `src/lib/vendored-protos.test.ts`), and that manifest went
# stale for a month -- it named 62baf6ec for a file that had become 68199ac9,
# so `sha256sum -c` reported the CURRENT, CORRECT contract as corrupt. A
# recorded value has to be regenerated by hand, and the hand forgets. Identity
# against the source of truth is DERIVED: there is nothing to regenerate, so
# there is nothing to forget. This repository already records the same lesson
# where `pending_enqueues_in_log()` replaced a cached counter.
#
# DIRECTION MATTERS, and the failure message says so: `backend/proto/` is
# authoritative because it is what protoc compiles into the engine. A mismatch
# is fixed by copying backend -> clients, never the reverse.
#
# SCOPE: every .proto under clients/*/proto/ must have a backend counterpart of
# the same name and identical bytes. A backend proto with no vendored copy is
# FINE -- calculator.proto and assistant.proto are not part of the mortgage
# client's surface. A vendored proto with NO backend counterpart is an error:
# "a dead entry beside a missing one reads exactly like coverage".
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

echo "============================================================"
echo "  VENDORED PROTO IDENTITY (clients/*/proto vs backend/proto)"
echo "============================================================"

failures=0
compared=0

while IFS= read -r vendored; do
    name="$(basename "${vendored}")"
    authoritative="backend/proto/${name}"

    if [[ ! -f "${authoritative}" ]]; then
        echo "[FAIL] ${vendored}"
        echo "       vendored but NOT PRESENT at ${authoritative}."
        echo "       Either it was renamed upstream or this copy is dead. A dead"
        echo "       entry beside a missing one reads exactly like coverage."
        failures=$((failures + 1))
        continue
    fi

    compared=$((compared + 1))
    if cmp -s "${authoritative}" "${vendored}"; then
        echo "[PASS] ${name} matches ${authoritative}"
    else
        echo "[FAIL] ${name} has DRIFTED from ${authoritative}"
        echo "       backend/proto is authoritative -- it is what protoc compiles"
        echo "       into the engine. Fix by copying that direction:"
        echo "           cp ${authoritative} ${vendored}"
        echo "       Difference (first 20 lines):"
        diff "${authoritative}" "${vendored}" | head -20 | sed 's/^/         /'
        failures=$((failures + 1))
    fi
done < <(find clients -mindepth 3 -maxdepth 3 -path '*/proto/*.proto' -print 2>/dev/null | sort)

# POSITIVE CONTROL. Without it this gate passes perfectly on a tree where the
# vendored directory was renamed, moved or emptied -- the `find` returns
# nothing, the loop never runs, and a green check reports on zero files. That
# is the failure that turns a gate into decoration.
if (( compared == 0 )); then
    echo "[FAIL] compared NOTHING -- no clients/*/proto/*.proto found."
    echo "       Has the vendored client moved? This gate is vacuous until it"
    echo "       inspects at least one contract."
    failures=$((failures + 1))
fi

echo "------------------------------------------------------------"
if (( failures == 0 )); then
    echo "OK -- ${compared} vendored contract(s) byte-identical to backend/proto"
    exit 0
fi
echo "FAILED -- ${failures} problem(s) across ${compared} compared contract(s)"
exit 1
