#!/usr/bin/env python3
"""Emit a mortgage-assistant evaluation as Prolog facts, DERIVED from the run.

    scripts/emit_assistant_facts.py <val.jsonl> <eval.json> [out.pl]

@author Olumuyiwa Oluwasanmi

Same contract as the sibling repository's emit-workflow-facts.mjs: the facts
are read out of the artefacts the run actually produced and out of
finance.proto itself, never retyped. A rule base maintained by hand beside the
thing it describes has the identical drift problem it exists to detect -- and
in this project that drift has a body count: a hand-written operation list in
ANOTHER repository once refused thirteen of the twenty-seven operations the
engine served.

What the facts describe, and why each one earns its place:

  label_space(Op)          the 27 operations derived from finance.proto
  excluded_field(Op, F)    a field the operation's request message declares and
                           that operation DISCARDS -- OP_EXCLUDED_FIELDS, the
                           mirror of mortgage_verification.cppm's
                           kOperationExcludedFields
  holdout_row(I, Op)       gold operation for held-out row I
  correct(I)               row I matched gold exactly (raw params)
  emitted(I, Op)           the operation the model actually named on row I
  emitted_field(I, F)      a key the model put in its <params> block
  refusal_shape(S, N)      how the service refused, and how often

The QUESTIONS are in assistant_check.cpp. Every one is written so that a
healthy run returns NO solutions, because a coverage defect is invisible to any
aggregate score: 400/508 says nothing about whether one operation is 0/11.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "agent" / "dataset"))

import build_mortgage_dataset as G  # noqa: E402


def atom(s: str) -> str:
    """Prolog atom: lower_snake, quoted if it cannot be bare."""
    t = "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in str(s))
    if not t or not t[0].isalpha():
        t = "x_" + t
    return t.lower()


def main() -> int:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2
    val_path, eval_path = Path(sys.argv[1]), Path(sys.argv[2])
    out_path = Path(sys.argv[3]) if len(sys.argv) > 3 else Path("/tmp/claude-1000/assistant-facts.pl")

    gold = []
    for line in val_path.read_text().splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        # The gold <params> live in the final assistant turn.
        op = ""
        for turn in reversed(row.get("conversations", [])):
            if turn.get("role") == "assistant":
                m = turn.get("content", "")
                i = m.find('"operation"')
                if i >= 0:
                    j = m.find('"', m.find(":", i) + 1)
                    k = m.find('"', j + 1)
                    op = m[j + 1:k]
                break
        gold.append(op)

    res = json.loads(eval_path.read_text())
    failures = {f["row"]: f for f in res.get("failures", [])}

    L = []
    L.append("% GENERATED by scripts/emit_assistant_facts.py -- do not edit.")
    L.append(f"% holdout: {val_path}")
    L.append(f"% eval   : {eval_path}")
    L.append("")

    for op in sorted(G.OPERATIONS):
        L.append(f"label_space({atom(op)}).")
    L.append("")
    for op, fields in sorted(G.OP_EXCLUDED_FIELDS.items()):
        for f in sorted(fields):
            L.append(f"excluded_field({atom(op)}, {atom(f)}).")
    L.append("")

    emitted_ops = set()
    for i, op in enumerate(gold):
        if not op:
            L.append(f"holdout_row({i}, non_params).")
        else:
            L.append(f"holdout_row({i}, {atom(op)}).")
        f = failures.get(i)
        if f is None:
            L.append(f"correct({i}).")
            if op:
                L.append(f"emitted({i}, {atom(op)}).")
                emitted_ops.add(op)
            continue
        got = f.get("got") or {}
        got_op = got.get("operation", "") if isinstance(got, dict) else ""
        if got_op:
            L.append(f"emitted({i}, {atom(got_op)}).")
            emitted_ops.add(got_op)
        if isinstance(got, dict):
            for key in sorted(k for k in got if k != "operation"):
                L.append(f"emitted_field({i}, {atom(key)}).")
    L.append("")
    for shape, n in sorted(res.get("refusal_shapes", {}).items()):
        L.append(f"refusal_shape({atom(shape)}, {n}).")
    L.append("")
    L.append(f"raw_exact({res.get('raw_exact', 0)}).")
    L.append(f"raw_total({res.get('raw_total', 0)}).")

    out_path.write_text("\n".join(L) + "\n")
    print(f"wrote {out_path}  "
          f"{len(G.OPERATIONS)} operations, {len(gold)} holdout rows, "
          f"{len(failures)} failures, {len(emitted_ops)} distinct operations emitted")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
