#!/usr/bin/env python3
"""Read `sensen-encoder.schema_json` out of the GGUF that is actually being served.

WHY THIS EXISTS. `scripts/score_encoder_served_rpc.py` read its schema from
`/tmp/parity_regen/schema.json`, a fixture written out of a training checkpoint. That is a
SECOND copy of the label space, in /tmp, with nothing binding it to the weights the engine
loaded -- and this project's scars are almost all of that shape: the four label-space
tables, `ALLOWED_OPERATIONS`' fifth copy in another repository, and the vendored-proto
manifest that named `62baf6ec` for a file that had become `68199ac9`, so `sha256sum -c`
reported the CORRECT contract as corrupt.

The schema travels INSIDE the GGUF for exactly this reason (the same argument that moved the
tokenizer in there: in a BERT vocabulary the token id IS the line number, so a second
artefact with its own path can renumber every token with nothing erroring). So read it from
there. A derived value cannot drift; a recorded one has to be regenerated by hand, and the
hand forgets.

This is a reader for the GGUF v3 metadata block only -- it stops before the tensor data and
never mmaps 4 MB of weights. Usage:

    encoder_schema_from_gguf.py backend/models/mortgage-encoder.gguf      # prints the JSON
    from encoder_schema_from_gguf import schema_json                      # as a library
"""
from __future__ import annotations

import json
import struct
import sys
from pathlib import Path

# GGUF v3 value types, as the format defines them.
_U8, _I8, _U16, _I16, _U32, _I32, _F32, _BOOL, _STR, _ARR, _U64, _I64, _F64 = range(13)
_FIXED = {_U8: "<B", _I8: "<b", _U16: "<H", _I16: "<h", _U32: "<I", _I32: "<i",
          _F32: "<f", _BOOL: "<B", _U64: "<Q", _I64: "<q", _F64: "<d"}


class _Cursor:
    def __init__(self, blob: bytes) -> None:
        self.b, self.at = blob, 0

    def take(self, n: int) -> bytes:
        if self.at + n > len(self.b):
            raise ValueError("GGUF metadata is truncated")
        out = self.b[self.at:self.at + n]
        self.at += n
        return out

    def u64(self) -> int:
        return struct.unpack("<Q", self.take(8))[0]

    def u32(self) -> int:
        return struct.unpack("<I", self.take(4))[0]

    def string(self) -> str:
        return self.take(self.u64()).decode("utf-8", "replace")

    def value(self, vtype: int):
        if vtype in _FIXED:
            fmt = _FIXED[vtype]
            v = struct.unpack(fmt, self.take(struct.calcsize(fmt)))[0]
            return bool(v) if vtype == _BOOL else v
        if vtype == _STR:
            return self.string()
        if vtype == _ARR:
            inner, n = self.u32(), self.u64()
            return [self.value(inner) for _ in range(n)]
        raise ValueError(f"unknown GGUF value type {vtype}")


def metadata(path: str | Path, read_bytes: int = 1 << 22) -> dict:
    """Every KV pair in the file's metadata block.

    Only the head of the file is read, which is why `read_bytes` exists: the metadata sits
    before the tensor data, so a few MB covers a schema of any size this project writes.
    A truncated read RAISES rather than returning what it managed to parse -- a partial
    schema would be a label space missing its tail, which reads as a model that forgot
    operations.
    """
    blob = Path(path).open("rb").read(read_bytes)
    c = _Cursor(blob)
    if c.take(4) != b"GGUF":
        raise ValueError(f"{path} is not a GGUF file")
    version = c.u32()
    if version != 3:
        raise ValueError(f"{path} is GGUF v{version}; this reader is written for v3")
    c.u64()  # tensor count, not needed here
    n_kv = c.u64()
    out: dict = {}
    for _ in range(n_kv):
        key = c.string()
        out[key] = c.value(c.u32())
    return out


def schema_json(path: str | Path) -> dict:
    kv = metadata(path)
    key = "sensen-encoder.schema_json"
    if key not in kv:
        raise SystemExit(
            f"REFUSED: {path} carries no {key}. Scoring against a schema from somewhere "
            f"else would compare the served answer to a label space this model may not "
            f"have -- which is the defect this reader exists to remove.")
    return json.loads(kv[key])


if __name__ == "__main__":
    if len(sys.argv) != 2:
        raise SystemExit("usage: encoder_schema_from_gguf.py <encoder.gguf>")
    print(json.dumps(schema_json(sys.argv[1]), separators=(",", ":"), sort_keys=True))
