#!/usr/bin/env python3
"""Score the mortgage assistant against the VISITOR REGRESSION corpus.

@author Olumuyiwa Oluwasanmi

    score_visitor_regression.py --target local:50871            # a native gRPC engine
    score_visitor_regression.py --target prod                   # https://api.optionsandfuturescalculator.com
    score_visitor_regression.py --self-test                     # prove the judge detects each defect class

The corpus is backend/tests/data/visitor_regression.jsonl (generated by
scripts/build_visitor_regression.py). Its header documents the CONTRACT it encodes: the assistant
returns only what the visitor stated or what follows from it, asks only for an ESSENTIAL missing
input, never refuses with "left out X", and computes calculations worded as questions.

WHAT IT PRINTS. One PASS/FAIL line per row with the reason, then totals by expected outcome, by
operation/group and by FAILURE CLASS:

    spurious_field     a field the visitor never stated (the form-overwriting zero)
    missing_field      a stated or essential field the answer omitted
    wrong_value        the right field with the wrong number
    wrong_operation    the right outcome kind naming the wrong calculation
    wrong_outcome      params / question / refusal when another was required (sub-typed)
    wrong_question     asked, but about something else
    left_out_refusal   the "The assistant left out X" refusal, which the contract forbids

PRODUCTION. Uses the partner key, which is read from --key-file and NEVER printed, with the
mortgagefvcalculator.com origin, at no more than --max-rps requests a second (default 2). A 429 is
waited out using the "retry in Ns" the engine names and retried; it is never scored as a failure.

TWO-TURN ROWS. `--two-turn-protocol engine` (default) sends turn 2 the way the ENGINE's contract
defines it: utterance = the ORIGINAL request, prior_question = the question the service asked,
prior_clarification = the visitor's reply. `site` sends it the way mortgage-nest-egg sends it today:
utterance = the REPLY, prior_clarification = the QUESTION, and the original request is not sent at
all -- which the engine cannot answer, and which is why that flag exists: it measures the break.

`--dispatch` also runs each answered params through sensen.finance.Finance and records whether the
RPC ACCEPTS them. mortgage-nest-egg passes the assistant's params to Finance unchanged, so a
stated-only answer that the RPC refuses is a field the client must complete -- evidence, not opinion.
"""
from __future__ import annotations

import argparse
import collections
import json
import re
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from decimal import Decimal, InvalidOperation
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CORPUS = ROOT / "backend" / "tests" / "data" / "visitor_regression.jsonl"
DEFAULT_KEY_FILE = Path("/home/muyiwa/Development/OptionsAndFuturesCalculator/config/keys/mortgagefv-key-2026-08-10.txt")
PROD_HOST = "https://api.optionsandfuturescalculator.com"
PROD_ORIGIN = "https://mortgagefvcalculator.com"
ASSISTANT_PATH = "/mortgage.assistant.MortgageAssistant/ParseOperation"

# What a clarifying question must read like, per field it may be asked about. Restated HERE,
# independently of mortgage_verification.cppm's clarifying_question(), so a reworded question
# that nothing else notices is a failure rather than being accepted because both sides read the
# same table.
ASK_WORDING = {
    "term": r"year|term|long|how many months",
    "rate": r"rate",
    "money": r"how much|loan|borrow|balance|owe|price|worth|value|cost|amount|put",
    "rent": r"rent",
    "payment": r"payment|pay",
    "tax": r"tax",
    "expenses": r"expense|operating|cost|run",
    "down": r"down",
    "component": r"interest|principal",
    "period": r"which|period|month|payment|year",
    "cash_flows": r"cash flow|invest|return|amount|how much",
    "dates": r"day|when|date",
    "savings": r"start|saving|contribut|invest|how much|add",
    "frequency": r"bi-?weekly|how often|frequency|per year",
    "ltv": r"loan-to-value|ltv",
}
ASK_FIELD_CLASS = {
    **{f: "term" for f in ("periods", "term_months", "loan_term_years", "new_term_years", "repayment_term_years",
                           "years", "holding_period_years", "target_years", "remaining_months", "life",
                           "recovery_period", "current_remaining_months")},
    **{f: "rate" for f in ("rate", "annual_rate", "loan_annual_rate", "new_annual_rate", "current_annual_rate",
                           "annual_mortgage_rate", "annual_appreciation_rate")},
    **{f: "money" for f in ("present_value", "loan_amount", "current_loan_balance", "current_mortgage_balance",
                            "property_price", "home_price", "home_value", "property_value", "current_property_value",
                            "cost", "lump_sum_payment", "future_value", "total_cash_invested", "drawn_amount")},
    **{f: "rent" for f in ("current_monthly_rent", "monthly_gross_rent", "periodic_gross_rent", "monthly_rent_saved")},
    **{f: "payment" for f in ("payment", "current_monthly_payment")},
    "annual_tax_rate": "tax", "periodic_operating_expenses": "expenses",
    "down_payment": "down", "down_payment_percent": "down", "component": "component",
    **{f: "period" for f in ("period", "start_period", "end_period", "year")},
    "values": "cash_flows", "dates": "dates",
    **{f: "savings" for f in ("annual_contribution", "current_principal")},
    "payments_per_year": "frequency", "max_ltv_rate": "ltv",
}


# ---------------------------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------------------------
def as_decimal(x):
    try:
        return Decimal(str(x).strip())
    except (InvalidOperation, ValueError):
        return None


def values_equal(expected: str, got: str) -> bool:
    """Numeric comparison for numbers and arrays, exact for enums and booleans."""
    e, g = str(expected).strip(), str(got).strip()
    if e.startswith("[") and g.startswith("["):
        try:
            ea, ga = json.loads(e), json.loads(g)
        except json.JSONDecodeError:
            return e == g
        return len(ea) == len(ga) and all(values_equal(str(x), str(y)) for x, y in zip(ea, ga))
    de, dg = as_decimal(e), as_decimal(g)
    if de is not None and dg is not None:
        tol = max(Decimal("1e-9"), Decimal("1e-9") * abs(de))
        return abs(de - dg) <= tol
    return e == g


def judge_params(alt: dict, actual: dict):
    """-> (ok, failure_class, reason) for ONE params alternative against an answered response."""
    if actual["operation"] != alt["operation"]:
        return False, "wrong_operation", f"named {actual['operation']}, wanted {alt['operation']}"
    exp, got = alt["params"], actual["params"]
    allowed = set(exp) | set(alt.get("optional", []))
    spurious = sorted(set(got) - allowed)
    if spurious:
        return False, "spurious_field", "fields the visitor never stated: " + ", ".join(
            f"{k}={got[k]}" for k in spurious)
    missing = sorted(set(exp) - set(got))
    if missing:
        return False, "missing_field", "omitted: " + ", ".join(missing)
    wrong = [k for k in exp if not values_equal(exp[k], got[k])]
    if wrong:
        return False, "wrong_value", "; ".join(f"{k}: wanted {exp[k]}, got {got[k]}" for k in wrong)
    return True, "", ""


def question_matches(asks: list, question: str) -> bool:
    if not asks:
        return bool(question.strip())
    for f in asks:
        cls = ASK_FIELD_CLASS.get(f)
        pattern = ASK_WORDING.get(cls, r".")
        if re.search(pattern, question, re.IGNORECASE):
            return True
    return False


# Words a VISITOR must never be shown. The UI renders a refusal's message and a clarification's
# question verbatim, so an operation name, a snake_case field name or a quoted field name in
# either is a leak of the engine's internals (observed live 2026-10-06: "left out
# \"property_price\", which ComputeRentVsBuy needs").
INTERNAL_TEXT = re.compile(r'Compute[A-Z]|_[a-z]+_|"[a-z]+_[a-z_]+"')


def visitor_text(actual: dict) -> str:
    if actual["kind"] == "refusal":
        return actual.get("message", "")
    if actual["kind"] == "clarification":
        return actual.get("question", "")
    return ""


def judge(expect: list, actual: dict):
    """Judge an actual response against a list of acceptable alternatives.

    -> (passed, failure_class, reason). The reported failure is that of the alternative closest to
    what was answered: same outcome kind first, then the same operation.
    """
    kind = actual["kind"]
    # The contract forbids this refusal outright: an essential field is asked about, a
    # non-essential one is omitted, and neither is ever "left out". It fails even where a refusal
    # would otherwise be an acceptable outcome.
    if kind == "refusal" and "left out" in actual.get("message", ""):
        return False, "left_out_refusal", actual["message"]
    leak = INTERNAL_TEXT.search(visitor_text(actual))
    if leak:
        return False, "internal_text_leak", f"the visitor would be shown {leak.group(0)!r} in: {visitor_text(actual)[:140]}"
    candidates = []
    for alt in expect:
        if alt["outcome"] == kind:
            if kind == "params":
                ok, cls, why = judge_params(alt, actual)
            elif kind == "clarification":
                if question_matches(alt.get("asks", []), actual["question"]):
                    ok, cls, why = True, "", ""
                else:
                    ok, cls, why = False, "wrong_question", f"asked {actual['question']!r}, wanted a question about {alt.get('asks')}"
            else:  # refusal
                reasons = alt.get("reasons", [])
                if not reasons or actual["reason"] in reasons:
                    ok, cls, why = True, "", ""
                else:
                    ok, cls, why = False, "wrong_outcome", f"refused {actual['reason']}, wanted one of {reasons}"
            if ok:
                return True, "", ""
            candidates.append((0 if (kind != "params" or alt.get("operation") == actual.get("operation")) else 1, cls, why))
    if candidates:
        candidates.sort(key=lambda c: c[0])
        return False, candidates[0][1], candidates[0][2]
    wanted = sorted({a["outcome"] for a in expect})
    if kind == "refusal" and "left out" in actual.get("message", ""):
        return False, "left_out_refusal", actual["message"]
    sub = {"params": "answered", "clarification": "asked", "refusal": "refused"}[kind]
    detail = actual.get("message") or actual.get("question") or ""
    if kind == "params":
        detail = actual["operation"]
    return False, f"wrong_outcome:{sub}", f"{sub} ({detail[:140]}), wanted {'/'.join(wanted)}"


# ---------------------------------------------------------------------------------------------
# Transports
# ---------------------------------------------------------------------------------------------
class RateLimited:
    def __init__(self, max_rps: float):
        self.interval = 1.0 / max_rps if max_rps > 0 else 0.0
        self.last = 0.0

    def wait(self):
        now = time.monotonic()
        if self.interval and now - self.last < self.interval:
            time.sleep(self.interval - (now - self.last))
        self.last = time.monotonic()


def read_key(path: Path) -> str:
    for line in path.read_text().splitlines():
        if re.match(r"^\s+key\s", line):
            return line.split(None, 1)[1].strip()
    raise SystemExit(f"no 'key' line in {path}")


def retry_after(text: str) -> int | None:
    m = re.search(r"retry in (\d+)\s*s", text)
    return int(m.group(1)) if m else None


class ProdTransport:
    def __init__(self, host: str, key: str, max_rps: float):
        self.host, self.key, self.limit = host.rstrip("/"), key, RateLimited(max_rps)

    def _post(self, path: str, body: dict):
        while True:
            self.limit.wait()
            req = urllib.request.Request(
                self.host + path, data=json.dumps(body).encode(),
                headers={"content-type": "application/json", "x-api-key": self.key, "origin": PROD_ORIGIN})
            try:
                with urllib.request.urlopen(req, timeout=60) as r:
                    return r.status, json.loads(r.read() or b"{}")
            except urllib.error.HTTPError as e:
                text = e.read().decode(errors="replace")
                if e.code == 429:
                    time.sleep((retry_after(text) or 5) + 1)
                    continue
                try:
                    return e.code, json.loads(text)
                except json.JSONDecodeError:
                    return e.code, {"message": text[:300]}

    def parse(self, utterance, prior_clarification="", prior_question=""):
        body = {"utterance": utterance}
        if prior_clarification:
            body["prior_clarification"] = prior_clarification
        if prior_question:
            body["prior_question"] = prior_question
        status, j = self._post(ASSISTANT_PATH, body)
        return normalise_json(j)

    def finance(self, operation, params):
        status, j = self._post(f"/sensen.finance.Finance/{operation}", finance_body(params))
        if status == 200 and "message" not in j:
            return True, ""
        return False, str(j.get("message", j))[:200]


def normalise_json(j: dict) -> dict:
    if "params" in j:
        p = j["params"]
        return {"kind": "params", "operation": p.get("operation", ""), "params": dict(p.get("params", {}))}
    if "clarification" in j:
        return {"kind": "clarification", "question": j["clarification"].get("question", "")}
    if "refusal" in j:
        r = j["refusal"]
        return {"kind": "refusal", "reason": r.get("reason", ""), "message": r.get("message", "")}
    return {"kind": "refusal", "reason": "TRANSPORT", "message": str(j)[:300]}


def finance_body(params: dict) -> dict:
    """The params map as a Finance request: an array arrives as a JSON-array STRING and a boolean as
    "true"/"false", exactly the coercion mortgage-nest-egg's coerceRequestForJson performs."""
    body = {}
    for k, v in params.items():
        if isinstance(v, str) and v.startswith("["):
            body[k] = json.loads(v)
        elif v in ("true", "false"):
            body[k] = (v == "true")
        else:
            body[k] = v
    return body


class LocalTransport:
    def __init__(self, port: int):
        import grpc  # noqa: WPS433
        sys.path.insert(0, str(ROOT / "agent" / "train"))
        import mortgage_assistant_pb2 as pb
        import mortgage_assistant_pb2_grpc as pbg
        self.grpc, self.pb = grpc, pb
        self.channel = grpc.insecure_channel(f"127.0.0.1:{port}")
        self.stub = pbg.MortgageAssistantStub(self.channel)
        self.port = port
        self._finance = None

    def parse(self, utterance, prior_clarification="", prior_question=""):
        req = self.pb.ParseRequest(utterance=utterance, prior_clarification=prior_clarification,
                                   prior_question=prior_question)
        try:
            r = self.stub.ParseOperation(req, timeout=60)
        except self.grpc.RpcError as e:
            return {"kind": "refusal", "reason": "TRANSPORT", "message": f"{e.code().name}: {e.details()}"}
        k = r.WhichOneof("outcome")
        if k == "params":
            return {"kind": "params", "operation": r.params.operation, "params": dict(r.params.params)}
        if k == "clarification":
            return {"kind": "clarification", "question": r.clarification.question}
        if k == "refusal":
            return {"kind": "refusal", "reason": self.pb.Refusal.Reason.Name(r.refusal.reason),
                    "message": r.refusal.message}
        return {"kind": "refusal", "reason": "EMPTY", "message": ""}

    def _finance_stub(self):
        if self._finance is None:
            tmp = Path(tempfile.mkdtemp(prefix="vr_finance_pb_"))
            subprocess.run([sys.executable, "-m", "grpc_tools.protoc", f"-I{ROOT / 'backend' / 'proto'}",
                            f"--python_out={tmp}", f"--grpc_python_out={tmp}", "finance.proto"], check=True)
            sys.path.insert(0, str(tmp))
            import finance_pb2, finance_pb2_grpc  # noqa: WPS433,E401
            self._finance = (finance_pb2, finance_pb2_grpc.FinanceStub(self.channel))
        return self._finance

    def finance(self, operation, params):
        from google.protobuf import json_format
        pb2, stub = self._finance_stub()
        method = getattr(stub, operation)
        rpc = next(m for m in pb2.DESCRIPTOR.services_by_name["Finance"].methods if m.name == operation)
        req_cls = getattr(pb2, rpc.input_type.name)
        try:
            req = json_format.ParseDict(finance_body(params), req_cls())
        except json_format.ParseError as e:
            return False, f"request did not parse: {e}"[:200]
        try:
            method(req, timeout=30)
            return True, ""
        except self.grpc.RpcError as e:
            return False, f"{e.code().name}: {e.details()}"[:200]


# ---------------------------------------------------------------------------------------------
# Running
# ---------------------------------------------------------------------------------------------
def run_row(t, row: dict, protocol: str, dispatch: bool) -> dict:
    res = {"id": row["id"], "group": row["group"], "kind": row["kind"], "utterance": row["utterance"]}
    if "turns" not in row:
        actual = t.parse(row["utterance"])
        passed, cls, why = judge(row["expect"], actual)
        res.update(actual=actual, passed=passed, failure_class=cls, reason=why)
    else:
        first = t.parse(row["utterance"])
        passed, cls, why = judge(row["turns"][0]["expect"], first)
        res.update(turn1=first)
        if not passed:
            res.update(actual=first, passed=False, failure_class=cls, reason="turn 1: " + why)
        else:
            reply = row["turns"][1]["reply"]
            question = first.get("question", "")
            if protocol == "engine":
                second = t.parse(row["utterance"], prior_clarification=reply, prior_question=question)
            else:  # site
                second = t.parse(reply, prior_clarification=question)
            passed, cls, why = judge(row["turns"][1]["expect"], second)
            res.update(actual=second, passed=passed, failure_class=cls, reason=("turn 2: " + why) if why else "")
    if dispatch and res["actual"]["kind"] == "params":
        ok, err = t.finance(res["actual"]["operation"], res["actual"]["params"])
        res["dispatch"] = {"ok": ok, "error": err}
    return res


def rejudge(rows: list, files: list, out_json, quiet_pass: bool) -> int:
    """Judge recorded answers again. A row with no recorded answer is reported MISSING, not passed."""
    recorded = {}
    for f in files:
        for line in f.read_text().splitlines():
            if line.strip():
                r = json.loads(line)
                recorded[r["id"]] = r
    results, missing = [], []
    for row in rows:
        rec = recorded.get(row["id"])
        if rec is None or "actual" not in rec:
            missing.append(row["id"])
            continue
        res = {"id": row["id"], "group": row["group"], "kind": row["kind"], "utterance": row["utterance"],
               "actual": rec["actual"]}
        if "turn1" in rec:
            res["turn1"] = rec["turn1"]
        if "dispatch" in rec:
            res["dispatch"] = rec["dispatch"]
        if "turns" in row:
            ok1, c1, w1 = judge(row["turns"][0]["expect"], rec.get("turn1", rec["actual"]))
            if not ok1:
                res.update(passed=False, failure_class=c1, reason="turn 1: " + w1)
            else:
                ok, c, w = judge(row["turns"][1]["expect"], rec["actual"])
                res.update(passed=ok, failure_class=c, reason=("turn 2: " + w) if w else "")
            res["expect_kinds"] = row["turns"][1]["expect"]
        else:
            ok, c, w = judge(row["expect"], rec["actual"])
            res.update(passed=ok, failure_class=c, reason=w)
            res["expect_kinds"] = row["expect"]
        results.append(res)
        if not res["passed"]:
            print(f"FAIL {res['id']:<10} {res['kind']:<7} [{res['failure_class']}] {res['reason']}\n"
                  f"       {res['utterance'][:150]}")
        elif not quiet_pass:
            print(f"PASS {res['id']:<10} {res['kind']:<7} {res['actual'].get('operation', res['actual']['kind'])}")
    if missing:
        print(f"\nNOT RECORDED ({len(missing)}): {' '.join(missing)}")
    summarise(results)
    if out_json:
        slim = [{k: v for k, v in r.items() if k != "expect_kinds"} for r in results]
        out_json.write_text("\n".join(json.dumps(r, separators=(",", ":")) for r in slim) + "\n")
    return 0 if results and all(r["passed"] for r in results) and not missing else 1


def summarise(results: list, out=sys.stdout):
    def pct(a, b):
        return f"{a}/{b}"
    total = len(results)
    ok = sum(r["passed"] for r in results)
    print(f"\nTOTAL {pct(ok, total)} passed", file=out)

    def table(title, keyf):
        d = collections.defaultdict(lambda: [0, 0])
        for r in results:
            k = keyf(r)
            d[k][1] += 1
            d[k][0] += r["passed"]
        print(f"\nBY {title}", file=out)
        for k in sorted(d):
            print(f"  {k:<44} {d[k][0]:>3}/{d[k][1]:<3}", file=out)

    def expected_kind(r):
        kinds = {a["outcome"] for a in (r.get("expect_kinds") or [])}
        return "/".join(sorted(kinds))
    table("EXPECTED OUTCOME", expected_kind)
    table("OPERATION / GROUP", lambda r: r["group"])
    table("ROW KIND", lambda r: r["kind"])
    fails = collections.Counter(r["failure_class"] for r in results if not r["passed"])
    print("\nFAILURE CLASSES", file=out)
    for k, v in fails.most_common():
        print(f"  {k:<28} {v}", file=out)
    disp = [r for r in results if "dispatch" in r]
    if disp:
        bad = [r for r in disp if not r["dispatch"]["ok"]]
        print(f"\nFINANCE DISPATCH of answered params: {len(disp) - len(bad)}/{len(disp)} accepted", file=out)
        by = collections.Counter((r["actual"]["operation"], r["dispatch"]["error"]) for r in bad)
        for (op, err), n in sorted(by.items()):
            print(f"  {op:<28} x{n:<3} {err}", file=out)


# ---------------------------------------------------------------------------------------------
# Self-test: the judge must detect each defect class and must not cry wolf
# ---------------------------------------------------------------------------------------------
def self_test() -> int:
    exp_pay = [{"outcome": "params", "operation": "ComputePayment",
                "params": {"present_value": "400000", "rate": "0.005416666666667", "periods": "360"},
                "optional": []}]
    good = {"kind": "params", "operation": "ComputePayment",
            "params": {"present_value": "400000", "rate": "0.005416666666666", "periods": "360"}}
    checks = []

    def check(name, got, want_pass, want_class=""):
        passed, cls, why = judge(*got)
        okay = (passed == want_pass) and (cls == want_class if not want_pass else True)
        checks.append(okay)
        print(f"  {'ok  ' if okay else 'FAIL'} {name}: passed={passed} class={cls!r} {why[:90]}")

    print("judge self-test")
    check("control: correct answer passes (15-place rate truncation tolerated)", (exp_pay, good), True)
    check("(i) a spurious field is detected",
          (exp_pay, {**good, "params": {**good["params"], "monthly_hoa": "0"}}), False, "spurious_field")
    check("(ii) a missing field is detected",
          (exp_pay, {**good, "params": {k: v for k, v in good["params"].items() if k != "periods"}}),
          False, "missing_field")
    check("(iii) a wrong operation is detected", (exp_pay, {**good, "operation": "ComputeRate"}),
          False, "wrong_operation")
    check("(iv) a wrong outcome kind is detected (asked instead of answered)",
          (exp_pay, {"kind": "clarification", "question": "Over how many years?"}), False, "wrong_outcome:asked")
    check("(iv) a wrong outcome kind is detected (answered instead of refused)",
          ([{"outcome": "refusal", "reasons": ["OUT_OF_SCOPE"]}], good), False, "wrong_outcome:answered")
    check("a wrong value is detected", (exp_pay, {**good, "params": {**good["params"], "periods": "180"}}),
          False, "wrong_value")
    check("an optional field may appear", ([{**exp_pay[0], "optional": ["future_value"]}],
          {**good, "params": {**good["params"], "future_value": "0"}}), True)
    check("an alternative may match", (exp_pay + [{"outcome": "clarification", "asks": ["periods"]}],
          {"kind": "clarification", "question": "Over how many years?"}), True)
    check("a question about the WRONG field is detected",
          ([{"outcome": "clarification", "asks": ["periods"]}],
           {"kind": "clarification", "question": "What's the interest rate?"}), False, "wrong_question")
    check("the forbidden 'left out' refusal is its own class", (exp_pay, {"kind": "refusal",
          "reason": "INVALID_PARAMETERS",
          "message": 'The assistant left out "property_price", which ComputeRentVsBuy needs.'}),
          False, "left_out_refusal")
    check("an array compares elementwise", ([{"outcome": "params", "operation": "ComputeIrr",
          "params": {"values": "[-100,30.5]"}, "optional": []}],
          {"kind": "params", "operation": "ComputeIrr", "params": {"values": "[-100.0,30.50]"}}), True)
    check("an operation name in a refusal is an internal-text leak even where a refusal is wanted",
          ([{"outcome": "refusal", "reasons": ["OUT_OF_SCOPE"]}],
           {"kind": "refusal", "reason": "OUT_OF_SCOPE", "message": "ComputeRentVsBuy cannot do that"}),
          False, "internal_text_leak")
    check("a quoted field name in a question is an internal-text leak",
          ([{"outcome": "clarification", "asks": []}],
           {"kind": "clarification", "question": 'What is the "property_price"?'}), False, "internal_text_leak")
    check("a snake_case field name in a refusal is an internal-text leak",
          ([{"outcome": "refusal", "reasons": []}],
           {"kind": "refusal", "reason": "OUT_OF_SCOPE", "message": "the annual_rate_x was unclear"}),
          False, "internal_text_leak")
    check("plain language passes the hygiene check",
          ([{"outcome": "refusal", "reasons": ["OUT_OF_SCOPE"]}],
           {"kind": "refusal", "reason": "OUT_OF_SCOPE",
            "message": "I don't give financial advice -- try 'what would a $420,000 loan at 6.25% cost per month'."}), True)
    check("a 429 retry hint is parsed", ([], {"kind": "refusal", "reason": "OUT_OF_SCOPE", "message": ""}),
          False, "wrong_outcome:refused")
    assert retry_after("quota exceeded ... retry in 15s") == 15 and retry_after("nothing") is None
    bad = checks.count(False)
    print(f"{len(checks) - bad}/{len(checks)} self-checks passed")
    return 1 if bad else 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--target", help="local:PORT | prod | https://host")
    ap.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    ap.add_argument("--key-file", type=Path, default=DEFAULT_KEY_FILE)
    ap.add_argument("--two-turn-protocol", choices=("engine", "site"), default="engine")
    ap.add_argument("--dispatch", action="store_true")
    ap.add_argument("--max-rps", type=float, default=2.0)
    ap.add_argument("--only", nargs="*", help="row ids or id prefixes")
    ap.add_argument("--json", type=Path, help="write per-row results here")
    ap.add_argument("--rejudge", type=Path, nargs="+",
                    help="re-score answers ALREADY recorded in these result files against the current corpus "
                         "instead of calling a service (several files are merged, later wins). Production's "
                         "partner budget is ~190 parses an hour shared with the live site, so a recorded run "
                         "is judged again rather than repeated.")
    ap.add_argument("--quiet-pass", action="store_true")
    ap.add_argument("--self-test", action="store_true")
    a = ap.parse_args()
    if a.self_test:
        return self_test()
    if not a.target and not a.rejudge:
        ap.error("--target (or --rejudge) is required")
    rows = [json.loads(l) for l in a.corpus.read_text().splitlines() if l.strip()]
    if a.only:
        rows = [r for r in rows if any(r["id"].startswith(p) for p in a.only)]
    if not rows:
        print("REFUSED: no corpus rows selected; a run that measures nothing is not a pass", file=sys.stderr)
        return 2
    if a.rejudge:
        return rejudge(rows, a.rejudge, a.json, a.quiet_pass)
    if a.target.startswith("local:"):
        t = LocalTransport(int(a.target.split(":", 1)[1]))
    else:
        host = PROD_HOST if a.target == "prod" else a.target
        t = ProdTransport(host, read_key(a.key_file), a.max_rps)
    results = []
    for row in rows:
        res = run_row(t, row, a.two_turn_protocol, a.dispatch)
        res["expect_kinds"] = row["expect"] if "turns" not in row else row["turns"][1]["expect"]
        results.append(res)
        if res["passed"]:
            if not a.quiet_pass:
                print(f"PASS {res['id']:<10} {res['kind']:<7} {res['actual'].get('operation', res['actual']['kind'])}")
        else:
            print(f"FAIL {res['id']:<10} {res['kind']:<7} [{res['failure_class']}] {res['reason']}\n"
                  f"       {res['utterance'][:150]}")
    summarise(results)
    if a.json:
        slim = [{k: v for k, v in r.items() if k != "expect_kinds"} for r in results]
        a.json.write_text("\n".join(json.dumps(r, separators=(",", ":")) for r in slim) + "\n")
    return 0 if all(r["passed"] for r in results) else 1


if __name__ == "__main__":
    raise SystemExit(main())
